// THE iOS SHELL MUST BE SHIPPABLE FROM THE REPO AS IT STANDS.
//
// The native side is the one deliverable no gate could see. Everything that
// decides what lands in the App Store is either generated by a Mac-only tool
// (Podfile.lock), gitignored and assembled at build time (native/www), or a
// config file whose most dangerous setting is a single absent key
// (server.url). All three have already gone wrong here, and none of them could
// fail a test, so each was found by a person noticing — or not noticing.
//
//   1. Podfile.lock rots. Apple Sign-In was added in full — the dependency in
//      native/package.json, the `pod` line in the Podfile, the plugin in
//      capacitor.config.json, the SignInWithApple calls in src/online/
//      identity.ts — and every one of those was committed. The lock was not. It
//      sat dirty for a day across several sessions, claimed by nobody, because
//      nothing could tell it apart from noise. Anyone building iOS off main got
//      a shell without the plugin the client code calls.
//   2. The web payload gets clobbered. `rsync dist/pwa/ → native/www/` replaces
//      the single-file build with the chunked PWA layout; this shipped
//      repeatedly on 2026-08-21 and was caught only by a build-tag mismatch
//      somebody happened to look at.
//   3. A dev build reaches the binary. Capacitor's live-reload writes a
//      server.url pointing at a laptop; ship that and the app loads from a
//      machine that is not there. It has never been committed here. This gate
//      is what keeps "never" true.
//
// Static on purpose, and pure Node: CocoaPods' PODFILE CHECKSUM is the SHA-1 of
// the Podfile it read, so "was this lock generated from THIS Podfile" is
// answerable without CocoaPods, without native/node_modules, and without a Mac.
//
// What it cannot see: whether pod sources resolve, what Xcode links, or what
// Apple actually receives. Those need a Mac and a real `pod install`. This
// proves the repo's own iOS manifests agree with each other and with the build.
import { existsSync, readFileSync } from 'node:fs';
import { APP_ID } from '../src/config.ts';
import { DEFAULT_AVATAR, PROFILE_AVATARS, appIconIdForAvatar } from '../src/profile-avatar.ts';
import { verifyIosPayloadContract } from './support/ios-payload-contract.ts';
import { verifyIosPodContract, verifyPodParsersCouldFail } from './support/ios-pod-contract.ts';
import { verifyIosShellContract } from './support/ios-shell-contract.ts';
import { verifyNodeRuntimeContract } from './support/node-runtime-contract.ts';
import { emitReport } from './support/emit-report.mjs';

const problems: string[] = [];
const errs: string[] = [];
const check = (ok: boolean, msg: string) => { if (!ok) problems.push(msg); };

const PKG = 'native/package.json';
const NATIVE_LOCK = 'native/package-lock.json';
const GC_PKG = 'native/plugins/gamecenter/package.json';
const GC_SWIFT = 'native/plugins/gamecenter/ios/Sources/GameCenterPlugin/GameCenterPlugin.swift';
const APP_ICON_PKG = 'native/plugins/appicon/package.json';
const APP_ICON_PODSPEC = 'native/plugins/appicon/KnucklebonesAppIcon.podspec';
const APP_ICON_SWIFT = 'native/plugins/appicon/ios/Sources/AppIconPlugin/AppIconPlugin.swift';
const ROOT_PKG = 'package.json';
const CONFIG = 'native/capacitor.config.json';
const SYNCED_CONFIG = 'native/ios/App/App/capacitor.config.json';
const INFO_PLIST = 'native/ios/App/App/Info.plist';
const REQUIRE_SYNCED = process.argv.includes('--require-synced');

const pkg = JSON.parse(readFileSync(PKG, 'utf8'));
const nativeLock = JSON.parse(readFileSync(NATIVE_LOCK, 'utf8'));
const gcPkg = JSON.parse(readFileSync(GC_PKG, 'utf8'));
const appIconPkg = JSON.parse(readFileSync(APP_ICON_PKG, 'utf8'));
const rootPkg = JSON.parse(readFileSync(ROOT_PKG, 'utf8'));
const capacitor = JSON.parse(readFileSync(CONFIG, 'utf8'));
/* ================= 0. BUILD/NATIVE BOUNDARY ================= */

const { nodePin, nodeRange } = verifyNodeRuntimeContract(check);
const nativePins: Record<string, string> = {
  '@capacitor/core': '8.5.0',
  '@capacitor/cli': '8.5.0',
  '@capacitor/ios': '8.5.0',
  '@capacitor/android': '8.5.0',
  '@capacitor/share': '8.0.1',
  '@capacitor/splash-screen': '8.0.2',
  '@capawesome/capacitor-apple-sign-in': '0.1.3',
  '@capacitor/assets': '3.0.5',
};
for (const [name, version] of Object.entries(nativePins)) {
  const declaredVersion = pkg.dependencies?.[name] ?? pkg.devDependencies?.[name];
  check(declaredVersion === version,
    `${PKG} must pin ${name} exactly to ${version}, found ${JSON.stringify(declaredVersion)}`);
  check(nativeLock.packages?.[`node_modules/${name}`]?.version === version,
    `${NATIVE_LOCK} must resolve the direct ${name} package to ${version}`);
}
check(rootPkg.scripts?.['native:sync'] === 'npm run build && npm --prefix native run sync',
  `${ROOT_PKG} native:sync must build then run the tracked native sync fail-fast`);
check(rootPkg.scripts?.['native:verify']?.includes('native:sync')
  && rootPkg.scripts?.['native:verify']?.includes('--require-synced'),
  `${ROOT_PKG} native:verify must sync first and require the generated Xcode payload`);

const GC_PACKAGE = 'knucklebones-game-center';
check(pkg.dependencies?.[GC_PACKAGE] === 'file:plugins/gamecenter',
  `${PKG} must install the tracked Game Center bridge as ${GC_PACKAGE}=file:plugins/gamecenter`);
check(nativeLock.packages?.['']?.dependencies?.[GC_PACKAGE] === 'file:plugins/gamecenter',
  `${NATIVE_LOCK} does not mirror ${PKG}'s local Game Center dependency`);
check(nativeLock.packages?.[`node_modules/${GC_PACKAGE}`]?.link === true
  && nativeLock.packages?.[`node_modules/${GC_PACKAGE}`]?.resolved === 'plugins/gamecenter',
  `${NATIVE_LOCK} does not lock ${GC_PACKAGE} to the tracked local plugin`);
check(gcPkg.name === GC_PACKAGE && gcPkg.capacitor?.ios?.src === 'ios',
  `${GC_PKG} must expose the ${GC_PACKAGE} Capacitor iOS package`);
const gcSwift = readFileSync(GC_SWIFT, 'utf8');
check(/@objc\(GameCenterPlugin\)/.test(gcSwift)
  && /jsName\s*=\s*["']GameCenter["']/.test(gcSwift)
  && /fetchItems\(forIdentityVerificationSignature:/.test(gcSwift)
  && /func initialize\(/.test(gcSwift)
  && /func getAuthState\(/.test(gcSwift)
  && /func fetchIdentityProof\(/.test(gcSwift)
  && /notifyListeners\("authStateChanged"/.test(gcSwift)
  && /player\.authenticateHandler\s*=/.test(gcSwift),
  `${GC_SWIFT} must provide the GameCenter bridge and Apple's signed identity payload`);

const APP_ICON_PACKAGE = 'knucklebones-app-icon';
check(pkg.dependencies?.[APP_ICON_PACKAGE] === 'file:plugins/appicon',
  `${PKG} must install the tracked profile-icon bridge as ${APP_ICON_PACKAGE}=file:plugins/appicon`);
check(nativeLock.packages?.['']?.dependencies?.[APP_ICON_PACKAGE] === 'file:plugins/appicon',
  `${NATIVE_LOCK} does not mirror ${PKG}'s local profile-icon dependency`);
check(nativeLock.packages?.[`node_modules/${APP_ICON_PACKAGE}`]?.link === true
  && nativeLock.packages?.[`node_modules/${APP_ICON_PACKAGE}`]?.resolved === 'plugins/appicon'
  && nativeLock.packages?.['plugins/appicon']?.name === APP_ICON_PACKAGE
  && nativeLock.packages?.['plugins/appicon']?.version === appIconPkg.version,
`${NATIVE_LOCK} does not lock ${APP_ICON_PACKAGE} to the tracked local plugin package`);
check(appIconPkg.name === APP_ICON_PACKAGE && appIconPkg.capacitorPlugin === true
  && appIconPkg.capacitor?.ios?.src === 'ios'
  && appIconPkg.files?.includes('KnucklebonesAppIcon.podspec'),
`${APP_ICON_PKG} must expose the tracked AppIcon Capacitor iOS package and podspec`);

const appIconPodspec = readFileSync(APP_ICON_PODSPEC, 'utf8');
check(/s\.name\s*=\s*['"]KnucklebonesAppIcon['"]/.test(appIconPodspec)
  && /s\.source_files\s*=\s*['"]ios\/Sources\/\*\*\/\*\.\{swift,h,m\}['"]/.test(appIconPodspec)
  && /s\.ios\.deployment_target\s*=\s*['"]15\.0['"]/.test(appIconPodspec)
  && /s\.dependency\s+['"]Capacitor['"]/.test(appIconPodspec)
  && /s\.frameworks\s*=\s*['"]UIKit['"]/.test(appIconPodspec),
`${APP_ICON_PODSPEC} must compile the Swift bridge against Capacitor/UIKit for iOS 15`);

const appIconSwift = readFileSync(APP_ICON_SWIFT, 'utf8');
const profileHues = [...new Set(PROFILE_AVATARS.map((avatar) => avatar.split(':')[2]))];
const swiftHueLiteral = (appIconSwift.match(/\bhues\s*=\s*\[([^\]]+)\]/) || [])[1] ?? '';
const swiftHues = [...swiftHueLiteral.matchAll(/["']([^"']+)["']/g)].map((match) => match[1]);
const expectedAlternates = PROFILE_AVATARS.map(appIconIdForAvatar).filter((icon) => icon !== 'primary');
const getStateContract = appIconSwift.slice(
  appIconSwift.indexOf('@objc func getState'),
  appIconSwift.indexOf('@objc func setIcon'),
);
const setIconContract = appIconSwift.slice(appIconSwift.indexOf('@objc func setIcon'));
const compareOffset = setIconContract.indexOf('if application.alternateIconName == desiredName');
const mutationOffset = setIconContract.indexOf('application.setAlternateIconName(desiredName)');
check(/@objc\(AppIconPlugin\)/.test(appIconSwift)
  && /identifier\s*=\s*["']AppIconPlugin["']/.test(appIconSwift)
  && /jsName\s*=\s*["']AppIcon["']/.test(appIconSwift)
  && /CAPPluginMethod\(name:\s*["']getState["'],\s*returnType:\s*CAPPluginReturnPromise\)/.test(appIconSwift)
  && /CAPPluginMethod\(name:\s*["']setIcon["'],\s*returnType:\s*CAPPluginReturnPromise\)/.test(appIconSwift),
`${APP_ICON_SWIFT} must expose promise-based AppIcon.getState/setIcon bridge methods`);
check(DEFAULT_AVATAR === 'die:5:cy' && expectedAlternates.length === 41
  && /primaryID\s*=\s*["']primary["']/.test(appIconSwift)
  && /profilePrimaryID\s*=\s*["']die-5-cy["']/.test(appIconSwift)
  && JSON.stringify(swiftHues) === JSON.stringify(profileHues)
  && /for face in 1\.\.\.6/.test(appIconSwift)
  && /if id != profilePrimaryID/.test(appIconSwift),
`${APP_ICON_SWIFT} allow-list must derive the exact 41 alternates while keeping die:5:cy primary`);
check(/UIApplication\.shared/.test(getStateContract)
  && /supportsAlternateIcons/.test(getStateContract)
  && /alternateIconName/.test(getStateContract)
  && /["']supported["']/.test(getStateContract) && /["']icon["']/.test(getStateContract)
  && !/["']changed["']/.test(getStateContract),
`${APP_ICON_SWIFT} getState must return only supported/current icon from UIKit`);
check(/guard requested != Self\.profilePrimaryID/.test(setIconContract)
  && /guard requested == Self\.primaryID \|\| Self\.alternateIDs\.contains\(requested\)/.test(setIconContract)
  && /requested == Self\.primaryID \? nil : requested/.test(setIconContract)
  && compareOffset >= 0 && mutationOffset > compareOffset
  && /["']supported["']/.test(setIconContract) && /["']icon["']/.test(setIconContract)
  && /["']changed["']/.test(setIconContract)
  && (appIconSwift.match(/DispatchQueue\.main\.async/g) ?? []).length >= 3,
`${APP_ICON_SWIFT} setIcon must validate, map primary to nil, compare first, mutate on main, and report changed`);
for (const code of [
  'invalid-icon', 'primary-as-alternate', 'unknown-current-icon',
  'unsupported', 'icon-change-failed', 'icon-state-mismatch',
]) {
  check(appIconSwift.includes(`"${code}"`), `${APP_ICON_SWIFT} must retain stable ${code} errors`);
}

/* ================= 1. APPLICATION IDENTITY + iOS SHELL ================= */

const { xcodeIds, gcBundle } = verifyIosShellContract(check);
const infoPlist = readFileSync(INFO_PLIST, 'utf8');
check(!infoPlist.includes('UIInterfaceOrientationLandscape')
  && /<key>UIRequiresFullScreen<\/key>\s*<true\s*\/>/.test(infoPlist)
  && /<key>UISupportedInterfaceOrientations<\/key>\s*<array>\s*<string>UIInterfaceOrientationPortrait<\/string>\s*<\/array>/.test(infoPlist),
`${INFO_PLIST} must explicitly opt the universal iPad target into portrait-only full screen`);

/* ================= 2. PODS ================= */

const pods = verifyIosPodContract(check);

/* ================= 3. THE WEB PAYLOAD ================= */
verifyIosPayloadContract(check, { requireSynced: REQUIRE_SYNCED });

/* ================= 4. NO DEV BUILD IN THE BINARY ================= */
/* Capacitor's live-reload writes server.url pointing at a dev machine. Ship it
   and the app loads from a laptop that is not there — or worse, is. */
if (existsSync(CONFIG)) {
  const server = capacitor.server ?? {};
  check(!('url' in server),
    `${CONFIG} sets server.url=${JSON.stringify(server.url)} — that is Capacitor `
    + `live-reload. A build with it loads the app from a dev machine instead of the `
    + `bundle. Remove it before shipping.`);
  check(server.cleartext !== true,
    `${CONFIG} sets server.cleartext=true — plaintext HTTP in a shipped app; this is `
    + `a live-reload setting that escaped.`);
  // the synced copy is what the binary reads
  const syncedConfig = SYNCED_CONFIG;
  if (REQUIRE_SYNCED) {
    check(existsSync(syncedConfig),
      `${syncedConfig} is absent — explicit native verification requires a successful cap sync`);
  }
  if (REQUIRE_SYNCED && existsSync(syncedConfig)) {
    const syncedCfg = JSON.parse(readFileSync(syncedConfig, 'utf8'));
    check(!('url' in (syncedCfg.server ?? {})),
      `the capacitor.config.json inside the Xcode project sets server.url — the binary `
      + `would load from a dev machine even though the repo config is clean`);
    check(syncedCfg.server?.cleartext !== true,
      `the capacitor.config.json inside the Xcode project enables cleartext HTTP`);
    const registered = syncedCfg.packageClassList ?? [];
    for (const plugin of [
      'AppleSignInPlugin', 'SplashScreenPlugin', 'SharePlugin', 'GameCenterPlugin', 'AppIconPlugin',
    ]) {
      check(registered.includes(plugin),
        `${syncedConfig} does not register ${plugin}; the corresponding native capability would be inert`);
    }
  }
}

verifyPodParsersCouldFail(check, pods);

emitReport({
  nodePin, nodeRange,
  appId: APP_ID, xcodeIds, gcBundle, requireSynced: REQUIRE_SYNCED,
  gameCenterPackage: GC_PACKAGE, appIconPackage: APP_ICON_PACKAGE,
  podfileSha: pods.podfileSha, stampedSha: pods.stamped,
  declared: Object.fromEntries(pods.declared), locked: Object.fromEntries(pods.locked),
  problems, errs,
}, problems.length || errs.length);
