import type { LocalizedLegalFact } from './types.ts';

/** Request-handling policy; operational verification is gated separately. */
export const ACCOUNT_REQUEST_VERIFICATION: LocalizedLegalFact = {
  en: 'We prefer authenticated in-app deletion. For requests by email we verify, where necessary, that you control the account or are authorized to act for its owner. A nickname alone is insufficient. We can request confirmation through the email address already verified for that account, or use the app’s sign-in and recovery options. We do not request passwords, tokens or blanket copies of identity documents. If we cannot identify the account or establish your authority, we explain the limitation and available next steps.',
  pt: 'Damos preferência à exclusão dentro do aplicativo, com a conta autenticada. Para pedidos por e-mail, verificamos, quando necessário, se você controla a conta ou tem autorização para agir em nome do titular. Só o apelido não basta. Podemos pedir uma confirmação pelo endereço de e-mail já verificado para essa conta ou usar as opções de login e recuperação do aplicativo. Não pedimos senhas nem tokens e não exigimos cópias de documentos de identidade de forma indiscriminada. Se não conseguirmos identificar a conta ou confirmar sua autorização, explicaremos essa limitação e os próximos passos disponíveis.',
  es: 'Preferimos la eliminación dentro de la aplicación con la cuenta autenticada. Para las solicitudes por correo, comprobamos cuando sea necesario que controlas la cuenta o tienes autorización para actuar en nombre de su titular. El apodo por sí solo no basta. Podemos pedir confirmación mediante la dirección de correo ya verificada para esa cuenta o utilizar las opciones de inicio de sesión y recuperación de la aplicación. No pedimos contraseñas ni tokens, ni exigimos copias de documentos de identidad de forma generalizada. Si no podemos identificar la cuenta o comprobar tu autorización, explicaremos la limitación y los siguientes pasos disponibles.',
  de: 'Wir bevorzugen die Löschung über eine authentifizierte Sitzung in der App. Bei Anfragen per E-Mail prüfen wir, soweit erforderlich, ob du die Kontrolle über das Konto hast oder für dessen Inhaber handeln darfst. Ein Nickname allein reicht nicht aus. Wir können eine Bestätigung über die bereits für das Konto verifizierte E-Mail-Adresse anfordern oder die Anmelde- und Wiederherstellungsoptionen der App nutzen. Wir verlangen weder Passwörter noch Tokens und fordern nicht pauschal Kopien von Ausweisdokumenten an. Können wir das Konto nicht zuordnen oder deine Berechtigung nicht feststellen, erklären wir diese Einschränkung und die verfügbaren nächsten Schritte.',
  fr: 'Nous privilégions la suppression dans l’application depuis une session authentifiée. Pour les demandes par e-mail, nous vérifions, si nécessaire, que vous contrôlez le compte ou êtes autorisé à agir pour son titulaire. Un pseudonyme seul ne suffit pas. Nous pouvons demander une confirmation via l’adresse e-mail déjà vérifiée pour ce compte ou utiliser les options de connexion et de récupération de l’application. Nous ne demandons ni mots de passe ni jetons et n’exigeons pas systématiquement de copies de pièces d’identité. Si nous ne pouvons pas identifier le compte ou établir votre autorisation, nous expliquons cette limite et les démarches possibles.',
  it: 'Preferiamo l’eliminazione nell’app da una sessione autenticata. Per le richieste via e-mail verifichiamo, quando necessario, che tu controlli l’account o abbia l’autorizzazione ad agire per il titolare. Il solo nickname non basta. Possiamo chiedere una conferma tramite l’indirizzo e-mail già verificato per quell’account oppure usare le opzioni di accesso e recupero dell’app. Non chiediamo password o token e non richiediamo in modo generalizzato copie dei documenti d’identità. Se non possiamo identificare l’account o accertare la tua autorizzazione, spieghiamo il limite e i passi successivi disponibili.',
  pl: 'Preferujemy usunięcie konta w aplikacji z uwierzytelnionej sesji. W przypadku wniosków e-mailowych w razie potrzeby sprawdzamy, czy kontrolujesz konto lub masz upoważnienie do działania w imieniu jego właściciela. Sam pseudonim nie wystarcza. Możemy poprosić o potwierdzenie przez adres e-mail już zweryfikowany dla tego konta lub skorzystać z opcji logowania i odzyskiwania w aplikacji. Nie prosimy o hasła ani tokeny i nie wymagamy od wszystkich kopii dokumentów tożsamości. Jeśli nie możemy zidentyfikować konta lub ustalić Twojego upoważnienia, wyjaśnimy to ograniczenie i dostępne dalsze kroki.',
  tr: 'Kimliği doğrulanmış bir oturum üzerinden uygulama içinde silmeyi tercih ederiz. E-postayla gelen taleplerde, gerektiğinde hesabı kontrol ettiğini veya sahibi adına hareket etme yetkin olduğunu doğrularız. Tek başına takma ad yeterli değildir. Bu hesap için daha önce doğrulanmış e-posta adresi üzerinden onay isteyebilir veya uygulamanın giriş ve kurtarma seçeneklerini kullanabiliriz. Parola ya da belirteç istemeyiz ve herkesten kimlik belgesi kopyası talep etmeyiz. Hesabı belirleyemez veya yetkini doğrulayamazsak bu sınırlamayı ve izlenebilecek sonraki adımları açıklarız.',
  id: 'Kami mengutamakan penghapusan di dalam aplikasi melalui sesi yang telah diautentikasi. Untuk permintaan lewat email, bila diperlukan kami memeriksa apakah Anda mengendalikan akun atau berwenang bertindak atas nama pemiliknya. Nama panggilan saja tidak cukup. Kami dapat meminta konfirmasi melalui alamat email yang sudah diverifikasi untuk akun tersebut atau menggunakan pilihan masuk dan pemulihan di aplikasi. Kami tidak meminta kata sandi atau token dan tidak mewajibkan semua orang mengirim salinan dokumen identitas. Jika kami tidak dapat mengidentifikasi akun atau memastikan kewenangan Anda, kami menjelaskan keterbatasan tersebut dan langkah berikutnya yang tersedia.',
  ja: '認証済みのセッションでアプリ内からアカウントを削除する方法を優先します。メールでの依頼については、必要に応じて、そのアカウントを管理していること、または所有者の代理として手続きする権限があることを確認します。ニックネームだけでは確認できません。そのアカウントですでに確認済みのメールアドレスを通じて確認をお願いするか、アプリのサインインや復旧機能を利用する場合があります。パスワードやトークンは求めず、本人確認書類の写しを一律に求めることもありません。アカウントを特定できない場合や権限を確認できない場合は、その制約と利用できる次の手順を説明します。',
  ko: '인증된 세션으로 앱 안에서 계정을 삭제하는 방식을 우선합니다. 이메일 요청은 필요한 경우 요청자가 계정을 관리하고 있거나 소유자를 대신해 요청할 권한이 있는지 확인합니다. 닉네임만으로는 충분하지 않습니다. 해당 계정에서 이미 인증된 이메일 주소로 확인을 요청하거나 앱의 로그인 및 복구 옵션을 이용할 수 있습니다. 비밀번호나 토큰을 요구하지 않으며 모든 요청자에게 일괄적으로 신분증 사본을 요구하지도 않습니다. 계정을 식별하거나 요청 권한을 확인할 수 없다면 그 한계와 가능한 다음 절차를 설명합니다.',
};
