import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { verifyAndroidProfileIconResources } from './android-profile-icon-contract.ts';
import { filesUnder } from './ios-artifacts.ts';
import {
  alphaBounds,
  alphaRowBounds,
  colorBounds,
  colorSpread,
  pixelAt,
  readPngPixels,
  rgbDistance,
} from './png-pixels.ts';
import { MASKABLE_ICON_PAD } from '../../tools/appicon.mjs';
import {
  LEFT_CELLS,
  RIGHT_CELLS,
  SPLIT_ICON_PAD,
  SPLIT_PIP_CELLS,
  pipPoint,
  platePoint,
  seamPoint,
} from './split-die-geometry.ts';

type Check = (ok: boolean, message: string) => void;

/* Launcher and splash art is generated by tools/appicon.mjs and tools/splash.mjs,
   so the questions worth asking of it are binary and observable: does every
   rendition survive into a CLEAN release checkout, does it carry the pixels,
   geometry, and alpha the launcher and splash system require, and does the
   generator still emit the Android 13 themed-launcher XML. */

function pngInfo(file: string): { width: number; height: number; colorType: number } | null {
  if (!existsSync(file)) return null;
  const bytes = readFileSync(file);
  if (bytes.length < 26 || bytes.subarray(1, 4).toString('ascii') !== 'PNG') return null;
  return {
    width: bytes.readUInt32BE(16),
    height: bytes.readUInt32BE(20),
    colorType: bytes[25]!,
  };
}

function ignored(file: string): boolean {
  try {
    execFileSync('git', ['check-ignore', '--quiet', '--', file]);
    return true;
  } catch {
    return false;
  }
}

export function verifyAndroidResourceContract(
  check: Check,
  res: string,
): { splashRenditions: number } {
  const densities: Array<[string, number]> = [
    ['ldpi', 36], ['mdpi', 48], ['hdpi', 72], ['xhdpi', 96],
    ['xxhdpi', 144], ['xxxhdpi', 192],
  ];
  for (const [density, size] of densities) {
    for (const name of [
      'ic_launcher.png',
      'ic_launcher_round.png',
      'ic_launcher_foreground.png',
      'ic_launcher_background.png',
      'ic_launcher_monochrome.png',
    ]) {
      const file = `${res}/mipmap-${density}/${name}`;
      const info = pngInfo(file);
      check(info?.width === size && info.height === size,
        `${file} must be a ${size}x${size} generated PNG, found ${JSON.stringify(info)}`);
      check(!ignored(file), `${file} is ignored and would be absent from a clean release checkout`);
    }
    const alpha = pngInfo(`${res}/mipmap-${density}/ic_launcher_monochrome.png`)?.colorType;
    check(alpha === 4 || alpha === 6,
      `${res}/mipmap-${density}/ic_launcher_monochrome.png must retain an alpha channel`);
  }

  verifyAndroidProfileIconResources(check, res);
  for (const [version, themed] of [['v26', false], ['v33', true]] as const) {
    for (const launcher of ['ic_launcher.xml', 'ic_launcher_round.xml']) {
      const file = `${res}/mipmap-anydpi-${version}/${launcher}`;
      const xml = readFileSync(file, 'utf8');
      check(xml.includes('<background android:drawable="@drawable/ic_launcher_background" />')
        && !/<background>[\s\S]*?<inset/.test(xml),
      `${file} must use the full-bleed adaptive gradient without an inset seam`);
      check(xml.includes('<inset android:drawable="@mipmap/ic_launcher_foreground" android:inset="10%" />'),
        `${file} must keep the adaptive foreground inside the launcher safe zone`);
      check(!themed || (xml.includes('<monochrome>')
        && xml.includes('<inset android:drawable="@mipmap/ic_launcher_monochrome" android:inset="10%" />')
        && !xml.includes('<monochrome android:drawable=')),
      `${file} must keep the Android 13 monochrome layer inside the launcher safe zone`);
      check(!ignored(file), `${file} is ignored and would not ship`);
    }
  }
  const adaptiveBackgroundFile = `${res}/drawable/ic_launcher_background.xml`;
  const adaptiveBackground = existsSync(adaptiveBackgroundFile)
    ? readFileSync(adaptiveBackgroundFile, 'utf8')
    : '';
  check(/<gradient[\s\S]*android:angle="270"[\s\S]*android:startColor="#313131"[\s\S]*android:endColor="#141414"/.test(adaptiveBackground),
    `${adaptiveBackgroundFile} must define the shared top-to-bottom dark gradient`);
  check(existsSync(adaptiveBackgroundFile) && !ignored(adaptiveBackgroundFile),
    `${adaptiveBackgroundFile} must be a tracked Android resource`);
  const representative = `${res}/mipmap-xxxhdpi`;
  const foreground = readPngPixels(`${representative}/ic_launcher_foreground.png`);
  const background = readPngPixels(`${representative}/ic_launcher_background.png`);
  const monochrome = readPngPixels(`${representative}/ic_launcher_monochrome.png`);
  const legacy = readPngPixels(`${representative}/ic_launcher.png`);
  const legacyRound = readPngPixels(`${representative}/ic_launcher_round.png`);
  const maskable = readPngPixels('public/icon-maskable-512.png');
  check(foreground.colorType === 6,
    'the Android adaptive foreground must retain alpha around and inside the die');
  check(background.colorType === 2 && !background.hasTransparency,
    'the Android adaptive background must remain an opaque RGB layer');
  check(monochrome.colorType === 6,
    'the Android themed-icon layer must retain alpha around and inside the die');
  check(maskable.colorType === 2 && !maskable.hasTransparency,
    'the PWA maskable launcher icon must remain an opaque, full-bleed RGB image');
  check(pixelAt(foreground, .03, .03).alpha <= 32 && pixelAt(monochrome, .03, .03).alpha === 0,
    'Android adaptive foregrounds must stay transparent outside the neon glow');
  const foregroundBounds = alphaBounds(foreground);
  const foregroundWidth = foregroundBounds
    ? (foregroundBounds.right - foregroundBounds.left + 1) / foreground.width
    : 0;
  check(foregroundBounds !== null && foregroundWidth >= .84 && foregroundWidth <= .89,
    `the Android split die should occupy about 86% of its layer including glow, found ${foregroundWidth}`);
  const topInk = alphaRowBounds(foreground, .4);
  const bottomInk = alphaRowBounds(foreground, .6);
  const topCenter = topInk ? (topInk.left + topInk.right) / (2 * foreground.width) : 0;
  const bottomCenter = bottomInk ? (bottomInk.left + bottomInk.right) / (2 * foreground.width) : 0;
  check(topInk !== null && bottomInk !== null
    && topCenter - bottomCenter >= .02 && topCenter - bottomCenter <= .036,
    `the Android die should have a subtle clockwise tilt, found row centers ${topCenter} and ${bottomCenter}`);
  const maskableBounds = colorBounds(maskable);
  const maskableWidth = maskableBounds
    ? (maskableBounds.right - maskableBounds.left + 1) / maskable.width
    : 0;
  check(maskableBounds !== null && maskableWidth >= .70 && maskableWidth <= .75,
    `the PWA maskable die's visible rounded bounds must stay inside its safe zone, found ${maskableWidth}`);
  /* THE SPLIT, on every Android surface: "your colour" lights the left pip
     column, the opponent's the right. A layer whose columns are one hue is
     the single-die mark this replaced. The pips are white-cored, so the hue
     shows as which side of white the pixel falls on. */
  const litLeft = (pixel: ReturnType<typeof pixelAt>): boolean =>
    pixel.green >= 235 && pixel.blue >= 245 && pixel.blue >= pixel.red;
  const litRight = (pixel: ReturnType<typeof pixelAt>): boolean =>
    pixel.red >= 250 && pixel.red - pixel.green >= 40;
  for (const [surface, pixels, pad] of [
    ['adaptive foreground', foreground, SPLIT_ICON_PAD],
    ['legacy launcher', legacy, SPLIT_ICON_PAD],
    ['round launcher', legacyRound, SPLIT_ICON_PAD],
    ['PWA maskable', maskable, MASKABLE_ICON_PAD],
  ] as const) {
    for (const cell of LEFT_CELLS) {
      const [x, y] = pipPoint(cell, pad);
      check(litLeft(pixelAt(pixels, x, y)),
        `the Android ${surface} pip at cell ${cell} must be lit and cast toward the p1 hue`);
    }
    for (const cell of RIGHT_CELLS) {
      const [x, y] = pipPoint(cell, pad);
      check(litRight(pixelAt(pixels, x, y)),
        `the Android ${surface} pip at cell ${cell} must be lit and cast toward the p2 hue`);
    }
    const [sx, sy] = seamPoint(.5, pad);
    const seam = pixelAt(pixels, sx, sy);
    check(Math.min(seam.red, seam.green, seam.blue) >= 225 && colorSpread(seam) <= 22,
      `the Android ${surface} lost the white seam between its two halves`);
  }
  /* The themed layer is tinted flat by the OS, so its whole meaning is the
     silhouette: six pip cutouts AND the seam, or it is an unmarked die. */
  for (const cell of SPLIT_PIP_CELLS) {
    const [x, y] = pipPoint(cell);
    for (const dx of [-.014, 0, .014]) {
      for (const dy of [-.014, 0, .014]) {
        check(pixelAt(monochrome, x + dx, y + dy).alpha === 0,
          `the Android themed-icon pip around cell ${cell} must be a substantial transparent cutout`);
      }
    }
  }
  for (const fy of [.3, .5, .7]) {
    const [x, y] = seamPoint(fy);
    check(pixelAt(monochrome, x, y).alpha === 0,
      `the Android themed icon must cut its seam at ${fy} of its height`);
  }
  const [monoBodyX, monoBodyY] = platePoint('left');
  const monoBody = pixelAt(monochrome, monoBodyX, monoBodyY);
  check(monoBody.alpha >= 220 && colorSpread(monoBody) <= 1,
    'the Android themed icon must keep a solid grayscale body between its cutouts');
  for (const raster of [legacy, legacyRound]) {
    const [lx, ly] = platePoint('left');
    const [rx, ry] = platePoint('right');
    const leftPlate = pixelAt(raster, lx, ly);
    const rightPlate = pixelAt(raster, rx, ry);
    check(leftPlate.green - leftPlate.red >= 80 && leftPlate.blue - leftPlate.red >= 90,
      'the Android legacy launcher left half must stand on the p1 plate');
    check(rightPlate.red - rightPlate.green >= 80 && rightPlate.red - rightPlate.blue >= 30,
      'the Android legacy launcher right half must stand on the p2 plate');
  }
  const backgroundTop = pixelAt(background, .5, .04);
  const backgroundBottom = pixelAt(background, .5, .96);
  check(rgbDistance(backgroundTop, backgroundBottom) >= 10
    && Math.max(backgroundTop.red, backgroundTop.green, backgroundTop.blue) <= 55
    && Math.max(backgroundBottom.red, backgroundBottom.green, backgroundBottom.blue) <= 35,
  'the Android adaptive background must use a soft dark gradient rather than a flat canvas');
  const iconGenerator = readFileSync('tools/appicon.mjs', 'utf8');
  const rootPackage = JSON.parse(readFileSync('package.json', 'utf8'));
  const androidAssetCommand = rootPackage.scripts?.['native:assets:android'] ?? '';
  const capacitorAssetsIndex = androidAssetCommand.indexOf('npm --prefix native run assets:android');
  const finalizerIndex = androidAssetCommand.indexOf('node tools/appicon.mjs --android-finalize');
  check(iconGenerator.includes('ANDROID_ADAPTIVE_ICON_FILES')
    && iconGenerator.includes('dieMarkup(face')
    && iconGenerator.includes("inlineCssGraph(['src/styles/main.css']")
    && iconGenerator.includes('mipmap-anydpi-v26/ic_launcher.xml')
    && iconGenerator.includes('mipmap-anydpi-v33/ic_launcher.xml')
    && iconGenerator.includes('mipmap-anydpi-v33/ic_launcher_round.xml')
    && iconGenerator.includes('drawable/ic_launcher_background.xml')
    && capacitorAssetsIndex >= 0
    && finalizerIndex > capacitorAssetsIndex,
  'the Android asset command must finalize both adaptive versions and their full-bleed gradient');
  const splashFiles = filesUnder(res).filter((file) => /(?:^|\/)splash\.png$/.test(file));
  check(splashFiles.length === 26,
    `Android must carry all 26 normal/night portrait/landscape splash renditions, found ${splashFiles.length}`);
  for (const file of splashFiles) {
    check(pngInfo(`${res}/${file}`) !== null, `${res}/${file} is not a readable PNG`);
    check(!ignored(`${res}/${file}`), `${res}/${file} is ignored and would not ship`);
  }
  const normalSplashFile = `${res}/drawable-port-mdpi/splash.png`;
  const darkSplashFile = `${res}/drawable-port-night-mdpi/splash.png`;
  const normalSplash = readFileSync(normalSplashFile);
  const darkSplash = readFileSync(darkSplashFile);
  check(createHash('sha256').update(normalSplash).digest('hex')
    === createHash('sha256').update(darkSplash).digest('hex'),
  'normal and dark Android loading screens must preserve the same dark branded continuity');
  const splashPixels = readPngPixels(normalSplashFile);
  const splashTop = pixelAt(splashPixels, .04, .04);
  const splashBottom = pixelAt(splashPixels, .04, .96);
  check(rgbDistance(splashTop, splashBottom) <= 3
    && rgbDistance(splashTop, { red: 5, green: 6, blue: 14, alpha: 255 }) <= 3,
  'the Android loading screen must preserve the app\'s #05060e first-frame continuity');
  const splashInkBounds = colorBounds(splashPixels);
  const splashInkWidthByHeight = splashInkBounds
    ? (splashInkBounds.right - splashInkBounds.left + 1) / splashPixels.height
    : 0;
  check(splashInkBounds !== null && splashInkWidthByHeight >= .182 && splashInkWidthByHeight <= .186,
    `the larger Android loading-screen neon die should occupy about 18.3% of its source height, found ${splashInkWidthByHeight}`);
  for (const [file, xEdges, yEdges] of [
    [normalSplashFile, [.32, .68], [.38, .62]],
    [`${res}/drawable-land-mdpi/splash.png`, [.38, .62], [.32, .68]],
  ] as const) {
    const pixels = readPngPixels(file);
    const centerX = Math.round((pixels.width - 1) * .5);
    const centerY = Math.round((pixels.height - 1) * .5);
    for (const edge of xEdges) {
      const x = Math.round(pixels.width * edge);
      check(rgbDistance(pixels.pixel(x - 1, centerY), pixels.pixel(x, centerY)) <= 4,
        `${file} has a clipped vertical edge in its loading-screen glow at ${edge}`);
    }
    for (const edge of yEdges) {
      const y = Math.round(pixels.height * edge);
      check(rgbDistance(pixels.pixel(centerX, y - 1), pixels.pixel(centerX, y)) <= 4,
        `${file} has a clipped horizontal edge in its loading-screen glow at ${edge}`);
    }
  }
  for (const [x, y] of [[.4496, .4569], [.5646, .4664], [.5, .5], [.4354, .5336], [.5504, .5431]]) {
    const pip = pixelAt(splashPixels, x, y);
    check(pip.red >= 150 && pip.green >= 240 && pip.blue >= 250,
      `the Android loading-screen pip at ${x},${y} must be filled and luminous`);
  }

  return { splashRenditions: splashFiles.length };
}
