import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { filesUnder } from './ios-artifacts.ts';

type Check = (ok: boolean, message: string) => void;

/* Launcher and splash art is generated by tools/appicon.mjs and tools/splash.mjs,
   so the questions worth asking of it are binary and structural: does every
   rendition survive into a CLEAN release checkout, does it carry the geometry
   and alpha the launcher and splash system require, and does the generator
   still emit the Android 13 themed-launcher XML. Reading PNG headers and
   `git check-ignore` keeps that answerable with no image library and no SDK. */

function pngInfo(file: string): { width: number; height: number; colorType: number } | null {
  if (!existsSync(file)) return null;
  const bytes = readFileSync(file);
  if (bytes.length < 26 || bytes.subarray(1, 4).toString('ascii') !== 'PNG') return null;
  return {
    width: bytes.readUInt32BE(16),
    height: bytes.readUInt32BE(20),
    colorType: bytes[25]!,
  };
}

function ignored(file: string): boolean {
  try {
    execFileSync('git', ['check-ignore', '--quiet', '--', file]);
    return true;
  } catch {
    return false;
  }
}

export function verifyAndroidResourceContract(
  check: Check,
  res: string,
): { splashRenditions: number } {
  const densities: Array<[string, number]> = [
    ['ldpi', 36], ['mdpi', 48], ['hdpi', 72], ['xhdpi', 96],
    ['xxhdpi', 144], ['xxxhdpi', 192],
  ];
  for (const [density, size] of densities) {
    for (const name of [
      'ic_launcher.png',
      'ic_launcher_round.png',
      'ic_launcher_foreground.png',
      'ic_launcher_background.png',
      'ic_launcher_monochrome.png',
    ]) {
      const file = `${res}/mipmap-${density}/${name}`;
      const info = pngInfo(file);
      check(info?.width === size && info.height === size,
        `${file} must be a ${size}x${size} generated PNG, found ${JSON.stringify(info)}`);
      check(!ignored(file), `${file} is ignored and would be absent from a clean release checkout`);
    }
    const alpha = pngInfo(`${res}/mipmap-${density}/ic_launcher_monochrome.png`)?.colorType;
    check(alpha === 4 || alpha === 6,
      `${res}/mipmap-${density}/ic_launcher_monochrome.png must retain an alpha channel`);
  }
  for (const launcher of ['ic_launcher.xml', 'ic_launcher_round.xml']) {
    const file = `${res}/mipmap-anydpi-v33/${launcher}`;
    check(readFileSync(file, 'utf8').includes('<monochrome android:drawable="@mipmap/ic_launcher_monochrome" />'),
      `${file} must expose the Android 13 monochrome launcher layer`);
    check(!ignored(file), `${file} is ignored and would not ship`);
  }
  const iconGenerator = readFileSync('tools/appicon.mjs', 'utf8');
  check(iconGenerator.includes('ANDROID_ADAPTIVE_ICON_FILES')
    && iconGenerator.includes('mipmap-anydpi-v33/ic_launcher.xml')
    && iconGenerator.includes('mipmap-anydpi-v33/ic_launcher_round.xml')
    && iconGenerator.includes('writeFileSync(file, ANDROID_ADAPTIVE_ICON_XML)'),
  'tools/appicon.mjs must regenerate both Android 13 themed-launcher XML resources');
  const splashFiles = filesUnder(res).filter((file) => /(?:^|\/)splash\.png$/.test(file));
  check(splashFiles.length === 26,
    `Android must carry all 26 normal/night portrait/landscape splash renditions, found ${splashFiles.length}`);
  for (const file of splashFiles) {
    check(pngInfo(`${res}/${file}`) !== null, `${res}/${file} is not a readable PNG`);
    check(!ignored(`${res}/${file}`), `${res}/${file} is ignored and would not ship`);
  }
  const normalSplash = readFileSync(`${res}/drawable-port-mdpi/splash.png`);
  const darkSplash = readFileSync(`${res}/drawable-port-night-mdpi/splash.png`);
  check(createHash('sha256').update(normalSplash).digest('hex')
    === createHash('sha256').update(darkSplash).digest('hex'),
  'normal and dark Android splash art must preserve the same #05060e branded continuity');

  return { splashRenditions: splashFiles.length };
}
