import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const DE_LEGAL: LegalLocaleContent = {
  siteTitle: 'Rechtliche Informationen zu Knucklebones Neon',
  languageLabel: 'Sprache',
  pageNavigationLabel: 'Rechtliche Informationen',
  languageNavigationLabel: 'Verfügbare Sprachen',
  homeLabel: 'Zurück zum Spiel',
  backLabel: 'Zurück',
  pendingFact: 'Vor Veröffentlichung noch zu prüfen',
  pages: {
    imprint: {
      title: 'Anbieterkennzeichnung',
      shortTitle: 'Impressum',
      description: 'Anbieter- und Kontaktangaben für Knucklebones Neon.',
      intro: 'Knucklebones Neon wird von der folgenden Privatperson angeboten.',
      sections: [
        { id: 'provider', heading: 'Anbieter gemäß § 18 Abs. 1 MStV', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'Kontakt', blocks: [p('E-Mail: {{publicEmail}}')] },
        { id: 'project', heading: 'Über das Projekt', blocks: [p('Knucklebones Neon ist ein kostenloses, nicht kommerzielles Hobbyspiel. Es gibt keine Werbung, Käufe, Abonnements oder Spenden.')] },
      ],
    },
    privacy: {
      title: 'Datenschutzhinweise',
      shortTitle: 'Datenschutz',
      description: 'Wie Knucklebones Neon Geräte-, Konto- und Online-Spieldaten verarbeitet.',
      intro: 'Lokal kannst du ohne Ranglistenkonto spielen. Für Online-Spiele wird ein Konto benötigt, um deinen Fortschritt zu speichern und Gegner zu finden. Hier erfährst du, welche Daten verwendet werden, wer sie erhält und wie du sie löschen kannst.',
      sections: [
        { id: 'controller', heading: 'Wer verantwortlich ist', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Bei Datenschutzfragen oder zur Ausübung deiner Rechte erreichst du uns unter {{publicEmail}}.')] },
        { id: 'scope', heading: 'Für welche Angebote diese Hinweise gelten', blocks: [p('Diese Hinweise gelten für die Website, die installierte Web-App, das eigenständige Spiel, das eingebettete Widget und die nativen Apps von Knucklebones Neon. Cloudflare liefert die Website und ihre Dateien aus. Native Apps laden ihre Spieldateien aus dem installierten Paket; Online-Funktionen verbinden sich weiterhin mit den jeweiligen Dienstleistern. Spielst du ein Widget auf einer anderen Website, kann diese Website zusätzlich Daten nach ihren eigenen Datenschutzhinweisen verarbeiten.'), p('Wir binden keine Werbung, verhaltensbezogene Analyse oder Tracking-SDKs ein. Das Spiel fragt weder Standort, Kontakte, Kamera noch Fotos ab und bietet keinen Spielerchat oder Bilder-Upload. Die Betriebs- und Sicherheitsdaten unserer Infrastrukturanbieter beschreiben wir weiter unten.')] },
        { id: 'device-storage', heading: 'Daten auf deinem Gerät', blocks: [p('Browser oder App speichern deine gewählte Sprache, Einstellungen zu Barrierefreiheit und Spiel sowie lokale Ergebnisse und Statistiken. Bei Online-Konten werden außerdem Sitzungsdaten und lokale Kopien deines Profils, verknüpfter Kontoinformationen, letzter Spiele, Runen und Fortschritte gespeichert. Diese Kontokopien liegen auch auf dem Server und sind nicht ausschließlich lokale Daten.'), p('Die Web-App speichert Spieldateien zwischen, damit sie offline funktioniert. Wird eine Programmdatei nicht richtig geladen, wird kurzzeitig auch ein Wiederherstellungsmerkmal gespeichert. Dafür werden unter anderem der lokale Browserspeicher, Sitzungsspeicher und App-Dateicache verwendet; es handelt sich nicht um Werbe-Cookies.'), p('Speicherung und Zugriff, die für eine von dir gewünschte Funktion unbedingt erforderlich sind, beruhen auf § 25 Abs. 2 Nr. 2 TDDDG. Für die Verarbeitung personenbezogener Daten gelten die unten genannten Zwecke und Rechtsgrundlagen. Zum Entfernen lokaler Daten folge der Anleitung für dein Gerät unter „Konto löschen“. Löschst du eine Gastsitzung ohne Wiederherstellungsmöglichkeit, kannst du den Zugang zu diesem Konto verlieren.')] },
        { id: 'accounts', heading: 'Gastkonten, E-Mail und Spielfortschritt', blocks: [p('Wenn du ein Ranglistenspiel anforderst, verwendet das Spiel dein vorhandenes Konto oder stellt es wieder her. Unter iOS wird dafür nach Möglichkeit deine verknüpfte Game-Center-Identität verwendet. Andernfalls entsteht ein Gastkonto, ohne dass Name oder E-Mail abgefragt werden. „Gast“ bedeutet nicht, dass die Daten anonym sind: Das Konto besitzt eine dauerhafte Kennung.'), p('Zu den Kontodaten gehören diese Kennung, ein erzeugter oder gewählter Nickname, ein vorgegebener Avatar, Einstellungen, aktuelle und höchste Punkte, Ranglistenergebnisse, Siege, Niederlagen, Serien, der Erstellungszeitpunkt des Profils sowie Spiele und Züge. Auch Runen, freigeschaltete Inhalte, Erfolge, wöchentliche Herausforderungen und weiterer Fortschritt werden gespeichert.'), p('Registrierung, Anmeldung und Wiederherstellung mit E-Mail und Passwort sind freiwillig. Supabase Auth verarbeitet dafür die E-Mail-Adresse und Passwort-Zugangsdaten. {{smtpProvider}} versendet Bestätigungs- und Wiederherstellungsnachrichten. Gastspiele sind ohne E-Mail möglich; dann stehen weniger Wiederherstellungswege zur Verfügung. Für Ranglistenspiele benötigte Konto- und Zugdaten können bei Nutzung dieser Funktion nicht weggelassen werden.')] },
        { id: 'apple', heading: 'Apple-Anmeldung und Game Center', blocks: [p('Unter iOS wird die Game-Center-Authentifizierung beim App-Start initialisiert. Apple kann deshalb bereits vor einem Ranglistenspiel Game-Center-Daten verarbeiten. Das Spiel verwendet Apples Anmeldestatus und eine auf das Entwicklerteam begrenzte Spielerkennung, um dein Ranglistenkonto wiederherzustellen oder zu verknüpfen und bei einem Wechsel des Game-Center-Kontos auf dem Gerät zu schützen. Signierte Prüfdaten werden über einen Cloudflare-Zugangsdienst an Supabase übermittelt. Über diese Integration erhalten wir weder deine Game-Center-Freunde noch dein Profilfoto oder deinen öffentlichen Profilnamen.'), p('Wählst du „Mit Apple anmelden“, übermittelt Apple eine Kontokennung, signierte Anmeldedaten und gegebenenfalls deine echte E-Mail-Adresse oder eine private Relay-Adresse von Apple. Ein Autorisierungscode wird ausgetauscht, damit die Verbindung später widerrufen werden kann. Der dabei erhaltene Aktualisierungsnachweis wird verschlüsselt in Supabase Vault gespeichert und ausschließlich zum Widerruf der Apple-Verbindung bei Kontolöschung verwendet.'), p('Apple betreibt seine Konto- und Game-Center-Dienste nach eigenen Bedingungen und Datenschutzinformationen: https://www.apple.com/legal/privacy/ und https://www.apple.com/legal/privacy/data/en/game-center/. Game Center steuerst du in den Einstellungen deines Apple-Geräts.')] },
        { id: 'purposes', heading: 'Zwecke und Rechtsgrundlagen', blocks: [p('Die für das gewünschte kostenlose Spiel, Kontozugang und Wiederherstellung, gespeicherten Fortschritt, Spielvermittlung, Spielprüfung und Ranglistenergebnisse erforderlichen Daten verarbeiten wir aufgrund berechtigter Interessen (Art. 6 Abs. 1 Buchst. f DSGVO). Unsere Interessen sind, die von dir gewählten Funktionen bereitzustellen, deinen Spielfortschritt zu erhalten und ein faires, zuverlässiges Spiel zu betreiben. Öffentliche Profilangaben beschränken sich auf die unten beschriebenen Spielinformationen; deinen echten Namen benötigen wir nicht.'), p('Notwendige Anfrage- und Sicherheitsdaten, etwa IP-Adressen, Anfragezeitpunkte, Browser- oder App-Angaben, Antwortstatus und Fehlerinformationen, verarbeiten wir zur Auslieferung des Dienstes, zur Missbrauchsabwehr, zur Begrenzung übermäßiger Anfragen und zur Fehleruntersuchung (Art. 6 Abs. 1 Buchst. f DSGVO). Soweit Daten zur Erfüllung unserer Pflichten bei Datenschutzanfragen benötigt werden, ist die Grundlage Art. 6 Abs. 1 Buchst. c DSGVO in Verbindung mit Art. 12–22 DSGVO.')] },
        { id: 'recipients', heading: 'Dienstleister und internationale Verarbeitung', blocks: [p('Supabase stellt die gehostete Authentifizierung, Datenbank, Echtzeit-Spielverbindungen und Serverfunktionen bereit. Datenbankregion: {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Kontonachrichten werden über {{smtpProvider}} versendet. Apple verarbeitet zusätzlich Daten für die oben beschriebenen Apple-Dienste. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'Was andere sehen können', blocks: [p('Mit Ranglistenspielen nimmst du an einer öffentlichen Rangliste teil. Nickname, vorgegebener Avatar, aktuelle und höchste Punkte, Rang beziehungsweise Apex, Siege, Niederlagen, gespielte Partien, beste Serie, Beitrittszeitpunkt und Ranglistenergebnisse können in Rangliste und Spielerkarten angezeigt werden. Diese öffentlichen Profilübersichten sind auch ohne angemeldetes Konto abrufbar. Wähle einen Nickname, der weder deinen echten Namen noch Kontaktdaten verrät.'), p('Deine E-Mail, Passwort-Zugangsdaten und Apple-Anmeldedaten sind nicht öffentlich. Die ausführliche Kontohistorie sieht nur der Kontoinhaber; beide Beteiligten können ihre gemeinsame Spiel- und Zughistorie einsehen.')] },
        { id: 'retention', heading: 'Wie lange Daten gespeichert werden', blocks: [p('Gastkonten und wiederherstellbare Konten haben derzeit keinen automatischen Ablauf bei Inaktivität. Konto- und Spieldaten bleiben bis zur Kontolöschung bestehen. Die Löschung beendet gegebenenfalls ein aktives Spiel und entfernt Konto, Profil, Einstellungen, Warteschlangen- und Ranglisteneinträge, Spiel- und Zughistorie, Runen und Fortschritt. Technische Belege zur Vermeidung doppelter Spielbefehle werden für die stündliche Bereinigung freigegeben, sobald sowohl die Erstellung des Belegs als auch das Ende des zugehörigen Spiels mehr als {{commandReceiptRetentionDays}} Tage zurückliegen.'), p('Nach Löschung eines mit Apple verknüpften Kontos wird ein noch für den automatischen Widerruf benötigter Nachweis für ein Wiederholungsfenster von bis zu {{appleRevocationRetryDays}} Tagen verschlüsselt aufbewahrt und anschließend durch die geplante Verarbeitung entfernt. Ein geplanter Dienst prüft alle {{appleRevocationScheduleMinutes}} Minuten auf ausstehende Wiederholungen; einzelne Versuche können später erfolgen. Kann der Widerruf nicht automatisch abgeschlossen werden, nutze die unter „Konto löschen“ beschriebene manuelle Anleitung.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('Lokale Offline-Einstellungen, Statistiken und zwischengespeicherte Spieldateien bleiben erhalten, bis du die App- oder Websitedaten löschst. Die Löschung des Serverkontos allein entfernt diese Offline-Daten nicht.')] },
        { id: 'support', heading: 'Support- und Datenschutzanfragen', blocks: [p('Wenn du uns kontaktierst, verarbeiten wir deine Absenderadresse, Nachricht und freiwillig beigefügte Angaben, etwa App-Version, Nickname oder Screenshot. Wir verwenden nur, was zur Beantwortung oder Untersuchung des gemeldeten Problems erforderlich ist (Art. 6 Abs. 1 Buchst. f DSGVO); die Grundlage für gesetzliche Datenschutzanfragen steht oben. Sende keine Passwörter oder Anmeldelinks.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'Deine Rechte', blocks: [p('Unter den jeweiligen gesetzlichen Voraussetzungen kannst du Auskunft über deine personenbezogenen Daten, Berichtigung, Löschung oder Einschränkung der Verarbeitung verlangen. Datenübertragbarkeit gilt, soweit automatisierte Verarbeitung auf Einwilligung oder einem Vertrag beruht. Beruht eine Verarbeitung auf Einwilligung, kannst du diese für die Zukunft widerrufen; die Rechtmäßigkeit der vorherigen Verarbeitung bleibt davon unberührt.'), p('Wende dich an {{publicEmail}}. Wir antworten grundsätzlich unverzüglich und innerhalb eines Monats. Ist eine gesetzlich zulässige Verlängerung erforderlich, erläutern wir dir den Grund innerhalb dieses ersten Monats. {{deletionVerification}}'), p('Du kannst dich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere an deinem Aufenthaltsort, Arbeitsplatz oder am Ort eines vermuteten Verstoßes. Für diesen Anbieter zuständig ist {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Informationen und Beschwerdekontakt: https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'Dein Widerspruchsrecht', blocks: [p('Soweit eine Verarbeitung auf Art. 6 Abs. 1 Buchst. f DSGVO beruht, kannst du ihr aus Gründen deiner besonderen Situation jederzeit widersprechen. Schreibe an {{publicEmail}}. Wir beenden diese Verarbeitung, sofern wir keine zwingenden schutzwürdigen Gründe nachweisen können, die deine Interessen, Rechte und Freiheiten überwiegen, oder die Verarbeitung zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist.')] },
        { id: 'children', heading: 'Kinder und Eltern', blocks: [p('Knucklebones Neon richtet sich an ein allgemeines Publikum. Es gibt keine Altersabfrage und es wird kein Geburtsdatum erfragt. Lokales Spielen benötigt kein Ranglistenkonto. Beim Online-Spiel werden die hier beschriebenen Konto- und Spieldaten gespeichert, auch bei jüngeren Spielenden.'), p('Wenn du jung bist: Verwende einen ausgedachten Nickname, halte dein Passwort geheim und bitte einen vertrauten Erwachsenen bei Konto- oder Datenschutzfragen um Hilfe. Andere Menschen können deinen Nickname und deine Spielergebnisse sehen. Im Spiel gibt es keinen Spielerchat, keine Werbung und keine Zahlungen.'), p('Eltern und Sorgeberechtigte können sich wegen eines Kinderkontos, einer Datenauskunft oder Löschung an {{publicEmail}} wenden. Wir erfragen nur Angaben, die zur Zuordnung des Kontos und zur Prüfung der Vertretungsberechtigung benötigt werden. Wo das anwendbare Recht eine elterliche Zustimmung verlangt, ersetzt weder die Nutzung eines Apple-Kontos noch das Weiterspielen diese Zustimmung.')] },
        { id: 'automated-decisions', heading: 'Spielvermittlung und automatische Berechnungen', blocks: [p('Das Spiel berechnet aus Spieldaten automatisch Punkte, Ränge, Freischaltungen und passende Gegner. Dabei kann auch ein computergesteuerter Gegner zugeteilt werden. Diese Spielfunktionen treffen keine Entscheidungen mit rechtlicher oder ähnlich erheblicher Wirkung für dich im Sinne von Art. 22 DSGVO.')] },
        { id: 'changes', heading: 'Stand und Änderungen', blocks: [p('Stand: {{noticeDate}}. Wir aktualisieren diese Hinweise, wenn sich das Spiel oder seine Datenverarbeitung ändert. Die aktuelle Fassung ist in der App und auf der öffentlichen Datenschutzseite erreichbar. Wesentliche Änderungen erläutern wir vor Beginn der geänderten Verarbeitung.')] },
      ],
    },
    support: {
      title: 'Support und Kontakt',
      shortTitle: 'Support',
      description: 'Hilfe zu Knucklebones Neon, Datenschutz und Konten.',
      intro: 'Kontaktiere uns bei Spielproblemen, Kontofragen oder Datenschutzanliegen.',
      sections: [
        { id: 'contact', heading: 'Kontakt', blocks: [p('E-Mail: {{publicEmail}}')] },
        { id: 'help', heading: 'Wobei wir helfen', blocks: [list('Technische Probleme und Barrierefreiheit', 'Ranglistenkonten und Nicknames', 'Datenschutzrechte und Kontolöschung', 'Sicherheits- oder Missbrauchsmeldungen', 'Fragen von Eltern zu einem Kinderkonto')] },
        { id: 'details', heading: 'Hilfreiche Angaben', blocks: [p('Beschreibe den Vorgang und nenne die App- oder Browserversion. Ergänze Nickname oder bestätigte Konto-E-Mail nur, wenn sie zum Auffinden des Kontos benötigt werden. Entferne private Angaben anderer Personen aus Screenshots.')] },
        { id: 'credentials', heading: 'Zugangsdaten geheim halten', blocks: [p('Sende niemals Passwort, Anmelde- oder Wiederherstellungslink, Zugriffstoken, Apple-Autorisierungscode oder private Daten anderer Personen. Wir fragen per E-Mail nicht nach solchen Zugangsdaten.')] },
        { id: 'handling', heading: 'Bearbeitung von Anfragen', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Gesetzliche Datenschutzanfragen beantworten wir grundsätzlich innerhalb eines Monats. Eine zulässige Verlängerung und ihren Grund erläutern wir innerhalb dieser Frist.')] },
      ],
    },
    'delete-account': {
      title: 'Konto löschen',
      shortTitle: 'Konto löschen',
      description: 'So löschst du ein Knucklebones-Neon-Ranglistenkonto in oder außerhalb der App.',
      intro: 'Die Löschung deines Ranglistenkontos ist endgültig. Du kannst anschließend weiterhin lokal spielen.',
      sections: [
        { id: 'in-app', heading: 'In der App löschen', blocks: [list('Öffne auf Home dein Profil.', 'Öffne die Kontoeinstellungen.', 'Wähle Konto löschen und lies die Erklärung.', 'Bestätige die endgültige Löschung.')] },
        { id: 'server-data', heading: 'Welche Daten gelöscht werden', blocks: [p('Das Spiel beendet gegebenenfalls eine aktive Partie und löscht dein gehostetes Konto, Profil, Einstellungen, Warteschlangen- und Ranglisteneinträge, Spiel- und Zughistorie, Runen und Fortschritt. Diese Ranglistenidentität und ihre Ergebnisse können über die App nicht wiederhergestellt werden.')] },
        { id: 'local-data', heading: 'Offline-Daten auf deinem Gerät', blocks: [p('Die Kontolöschung meldet dich ab und entfernt die lokale Kontositzung sowie das zwischengespeicherte Profil. Offline-Einstellungen, Statistiken und zwischengespeicherte Spieldateien bleiben erhalten. Um auch diese zu entfernen, lösche die Websitedaten im Browser. Unter Android kannst du den Speicher beziehungsweise die Daten der App in den Geräteeinstellungen löschen. Unter iOS lösche die App; beim Auslagern bleiben ihre Dokumente und Daten erhalten. Das Löschen der Gerätedaten allein löscht das Serverkonto nicht.')] },
        { id: 'external', heading: 'Löschung ohne App anfordern', blocks: [p('Schreibe an {{publicEmail}}, dass du dein Knucklebones-Neon-Ranglistenkonto löschen lassen möchtest. Verwende möglichst die bestätigte Konto-E-Mail, wenn du noch Zugriff darauf hast. Nenne den Nickname nur, falls er zum Auffinden benötigt wird. Sende keine Zugangsdaten. Eltern oder Sorgeberechtigte können sich auch wegen eines Kinderkontos melden.')] },
        { id: 'verification', heading: 'Inhaberprüfung und verbleibende Kopien', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Ein mit Apple verknüpftes Konto', blocks: [p('Bei der Löschung wird auch versucht, die Verbindung für „Mit Apple anmelden“ zu widerrufen. Bei vorübergehenden Fehlern erfolgen für bis zu {{appleRevocationRetryDays}} Tage weitere Versuche. Kann der automatische Widerruf nicht abgeschlossen werden, befolge die Anleitung in der App oder entferne die App-Verbindung in deinen Apple-Kontoeinstellungen. Dein Apple-Konto selbst wird nicht gelöscht. Auch dein separates Game-Center-Konto bleibt bestehen.')] },
      ],
    },
  },
};
