import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const ES_LEGAL: LegalLocaleContent = {
  siteTitle: 'Información legal de Knucklebones Neon',
  languageLabel: 'Idioma',
  pageNavigationLabel: 'Información legal',
  languageNavigationLabel: 'Idiomas disponibles',
  homeLabel: 'Volver al juego',
  backLabel: 'Volver',
  pendingFact: 'Pendiente de verificación antes de publicarse',
  pages: {
    imprint: {
      title: 'Información del responsable',
      shortTitle: 'Aviso legal',
      description: 'Datos del responsable y de contacto de Knucklebones Neon.',
      intro: 'La siguiente persona física es responsable de Knucklebones Neon.',
      sections: [
        { id: 'provider', heading: 'Responsable según el artículo 18.1 MStV', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'Contacto', blocks: [p('Correo electrónico: {{publicEmail}}')] },
        { id: 'project', heading: 'Acerca de este proyecto', blocks: [p('Knucklebones Neon es un juego gratuito desarrollado como afición y sin fines comerciales. No tiene publicidad, compras, suscripciones ni donaciones.')] },
      ],
    },
    privacy: {
      title: 'Aviso de privacidad',
      shortTitle: 'Privacidad',
      description: 'Cómo trata Knucklebones Neon los datos del dispositivo, de la cuenta y del juego en línea.',
      intro: 'Puedes jugar en local sin una cuenta para partidas clasificatorias. El juego en línea necesita una cuenta para guardar tu progreso y emparejarte con rivales. Este aviso explica qué datos se utilizan, quién los recibe y cómo puedes eliminarlos.',
      sections: [
        { id: 'controller', heading: 'Quién es responsable', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Para consultas o solicitudes de privacidad, escribe a {{publicEmail}}.')] },
        { id: 'scope', heading: 'Dónde se aplica este aviso', blocks: [p('Este aviso abarca el sitio web, la aplicación web instalada, el juego independiente, el widget integrado y las aplicaciones nativas de Knucklebones Neon. Cloudflare sirve el sitio web y sus archivos. Las aplicaciones nativas cargan los archivos del juego desde el paquete instalado, pero las funciones en línea siguen conectándose con sus proveedores de servicios. Si juegas con un widget en otro sitio web, ese sitio también puede tratar datos conforme a su propio aviso de privacidad.'), p('No integramos publicidad, análisis de comportamiento ni SDK de seguimiento. El juego no solicita tu ubicación, contactos, cámara ni fotos, y no tiene chat entre jugadores ni permite subir imágenes. Los datos operativos y de seguridad que tratan nuestros proveedores de infraestructura se describen más abajo.')] },
        { id: 'device-storage', heading: 'Datos almacenados en tu dispositivo', blocks: [p('El navegador o la aplicación guarda el idioma elegido, los ajustes de accesibilidad y del juego, y las puntuaciones y estadísticas locales. Para las cuentas en línea, también guarda credenciales de sesión y copias locales de tu perfil, información de cuentas vinculadas, partidas recientes, runas y progreso. Estas copias de la cuenta también se conservan en el servidor; no son datos exclusivamente locales.'), p('La aplicación web guarda archivos del juego en caché para funcionar sin conexión. También almacena brevemente una marca de recuperación cuando un archivo del programa no se carga. Estos usos incluyen el almacenamiento local del navegador, el almacenamiento de sesión y la caché de archivos de la aplicación; no son cookies publicitarias.'), p('El almacenamiento y el acceso necesarios para ofrecer una función que solicitas se basan en el artículo 25.2.2 TDDDG. El tratamiento de datos personales para esas funciones sigue las finalidades y bases jurídicas que se indican más abajo. Para eliminar los datos locales, sigue las instrucciones específicas para tu dispositivo en Eliminar cuenta. Borrar una sesión de invitado sin opción de recuperación puede impedir que vuelvas a acceder a esa cuenta.')] },
        { id: 'accounts', heading: 'Cuentas de invitado, correo y progreso', blocks: [p('Cuando solicitas jugar una partida clasificatoria, el juego utiliza o restaura tu cuenta existente. Cuando es posible en iOS, utiliza tu identidad vinculada de Game Center. En caso contrario, crea una cuenta de invitado sin pedir tu nombre ni correo electrónico. «Invitado» no significa que los datos sean anónimos: la cuenta tiene un identificador persistente.'), p('Los datos de la cuenta incluyen el identificador, un apodo generado o elegido, un avatar predefinido, ajustes, puntuación actual y máxima, resultados clasificatorios, victorias, derrotas, rachas, fecha y hora de creación del perfil, partidas y movimientos. También se guardan runas, contenido desbloqueado, logros, desafíos semanales y otros datos de progreso.'), p('El registro, el inicio de sesión y la recuperación con correo y contraseña son opcionales. Supabase Auth trata la dirección de correo electrónico y las credenciales de contraseña para estas funciones. {{smtpProvider}} entrega los mensajes de confirmación y recuperación de la cuenta. Puedes jugar como invitado sin proporcionar un correo, pero las opciones de recuperación serán limitadas. Los datos necesarios de la cuenta en línea y de los movimientos no pueden omitirse al jugar partidas clasificatorias.')] },
        { id: 'apple', heading: 'Iniciar sesión con Apple y Game Center', blocks: [p('En iOS, la autenticación de Game Center se inicializa al abrir la aplicación. Por ello, Apple puede tratar datos de Game Center antes de que inicies una partida clasificatoria. El juego utiliza el estado de autenticación de Apple y un identificador de jugador limitado al equipo de desarrollo para restaurar o vincular tu cuenta clasificatoria y protegerla cuando cambia la cuenta de Game Center del dispositivo. Los datos de verificación firmados pasan por una pasarela de Cloudflare hasta Supabase. Esta integración no nos proporciona tus amigos, foto de perfil ni nombre de perfil público de Game Center.'), p('Si eliges Iniciar sesión con Apple, Apple proporciona un identificador de cuenta, datos de autenticación firmados y, cuando se facilita, tu dirección de correo real o la dirección del servicio de retransmisión privada de Apple. Se intercambia un código de autorización para permitir la revocación posterior. La credencial de actualización resultante se cifra en Supabase Vault y se utiliza únicamente para revocar la conexión con Apple cuando eliminas la cuenta.'), p('Apple gestiona sus servicios de cuenta y Game Center conforme a sus propias condiciones e información de privacidad: https://www.apple.com/legal/privacy/ y https://www.apple.com/legal/privacy/data/en/game-center/. Puedes controlar Game Center en los ajustes de tu dispositivo Apple.')] },
        { id: 'purposes', heading: 'Por qué tratamos datos y con qué bases jurídicas', blocks: [p('Tratamos los datos necesarios para el juego gratuito solicitado, el acceso y la recuperación de la cuenta, el progreso guardado, el emparejamiento, la validación de partidas y los resultados clasificatorios sobre la base de intereses legítimos (artículo 6.1.f del RGPD). Nuestros intereses son proporcionar las funciones que eliges, conservar tu progreso y mantener un juego justo y fiable. La información pública del perfil se limita a los datos del juego descritos más abajo; no necesitamos tu nombre real.'), p('También tratamos los datos necesarios de solicitudes y seguridad, como direcciones IP, horas de las solicitudes, información del navegador o la aplicación, estado de las respuestas e información sobre errores, para prestar el servicio, evitar usos indebidos, limitar solicitudes excesivas e investigar fallos (artículo 6.1.f del RGPD). Para solicitudes relativas a derechos de privacidad, el tratamiento necesario para cumplir nuestras obligaciones se basa en el artículo 6.1.c en relación con los artículos 12 a 22 del RGPD.')] },
        { id: 'recipients', heading: 'Proveedores de servicios y tratamiento internacional', blocks: [p('Supabase proporciona autenticación alojada, base de datos, conexiones de juego en tiempo real y funciones de servidor. Región de la base de datos: {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Los correos de la cuenta se envían a través de {{smtpProvider}}. Apple también trata datos para los servicios de Apple descritos anteriormente. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'Qué pueden ver otras personas', blocks: [p('Al jugar partidas clasificatorias, participas en una clasificación pública. Tu apodo, avatar predefinido, puntuación actual y máxima, puesto o condición en la cima de la clasificación, victorias, derrotas, partidas jugadas, mejor racha, fecha de incorporación y resultados clasificatorios pueden aparecer en la clasificación y en las tarjetas de jugador. Estos resúmenes públicos del perfil también pueden consultarse sin iniciar sesión en una cuenta. Elige un apodo que no revele tu nombre real ni datos de contacto.'), p('Tu correo, tus credenciales de contraseña y tus datos de autenticación de Apple no son públicos. El historial detallado de la cuenta solo es visible para su titular; los dos participantes pueden acceder al historial de la partida y los movimientos que han compartido.')] },
        { id: 'retention', heading: 'Cuánto tiempo se conservan los datos', blocks: [p('Actualmente, las cuentas de invitado y las cuentas recuperables no caducan automáticamente por inactividad. Los datos de la cuenta y del juego se conservan hasta que se elimina la cuenta. La eliminación resuelve cualquier partida activa y borra la cuenta, el perfil, los ajustes, las entradas en la cola y en la clasificación, el historial de partidas y movimientos, las runas y el progreso. Los registros técnicos utilizados para evitar comandos de juego duplicados pueden eliminarse mediante la limpieza que se ejecuta cada hora cuando tanto su creación como el final de la partida correspondiente ocurrieron hace más de {{commandReceiptRetentionDays}} días.'), p('Tras eliminar una cuenta vinculada a Apple, cualquier credencial que siga siendo necesaria para la revocación automática se conserva cifrada durante un plazo de reintentos de hasta {{appleRevocationRetryDays}} días y después se elimina mediante el procesamiento programado. El procesamiento programado se ejecuta cada {{appleRevocationScheduleMinutes}} minutos; los reintentos individuales pueden realizarse más tarde. Si la revocación no puede completarse automáticamente, utiliza las instrucciones manuales descritas en Eliminar cuenta.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('Los ajustes locales sin conexión, las estadísticas y los archivos del juego en caché permanecen hasta que borras los datos de la aplicación o del sitio en el navegador. Eliminar solo la cuenta del servidor no borra esos elementos sin conexión.')] },
        { id: 'support', heading: 'Asistencia y solicitudes de privacidad', blocks: [p('Si contactas con nosotros, tratamos tu dirección de remitente, tu mensaje y la información que decidas incluir, como la versión de la aplicación, tu apodo o una captura de pantalla. Utilizamos solo lo necesario para atender tu consulta o investigar el problema comunicado (artículo 6.1.f del RGPD); la base jurídica para las solicitudes de derechos de privacidad previstos por la ley se describe más arriba. No envíes contraseñas ni enlaces de autenticación.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'Tus derechos', blocks: [p('Conforme a las condiciones legales aplicables, puedes solicitar acceso a tus datos personales, su rectificación, supresión o la limitación del tratamiento. La portabilidad de los datos se aplica cuando el tratamiento es automatizado y se basa en el consentimiento o en un contrato. Si el tratamiento se basa en el consentimiento, puedes retirarlo con efectos futuros sin afectar a la licitud del tratamiento anterior.'), p('Contacta con {{publicEmail}}. Normalmente respondemos sin dilación indebida y en el plazo de un mes. Si es necesaria una prórroga legalmente permitida, explicaremos el motivo dentro de ese primer mes. {{deletionVerification}}'), p('Puedes presentar una reclamación ante una autoridad de protección de datos, incluida la del lugar donde resides, trabajas o crees que se ha producido una infracción. La autoridad competente para este responsable es {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Información y contacto para reclamaciones: https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'Tu derecho de oposición', blocks: [p('Cuando el tratamiento se basa en el artículo 6.1.f del RGPD, puedes oponerte en cualquier momento por motivos relacionados con tu situación particular. Escribe a {{publicEmail}}. Dejaremos de realizar ese tratamiento, salvo que podamos acreditar motivos legítimos imperiosos que prevalezcan sobre tus intereses, derechos y libertades, o que el tratamiento sea necesario para la formulación, el ejercicio o la defensa de reclamaciones.')] },
        { id: 'children', heading: 'Menores, madres, padres y tutores', blocks: [p('Knucklebones Neon es un juego para el público general. No pregunta la edad ni solicita la fecha de nacimiento. Para jugar en local no se necesita una cuenta clasificatoria. El juego en línea sí guarda la información de la cuenta y del juego descrita aquí, también la de jugadores más jóvenes.'), p('Si eres joven: utiliza un apodo inventado, mantén tu contraseña en secreto y pide ayuda a un adulto de confianza si tienes dudas sobre tu cuenta o privacidad. Otras personas pueden ver tu apodo y tus resultados. Este juego no tiene chat entre jugadores, publicidad ni pagos.'), p('Las madres, los padres y los tutores pueden contactar con {{publicEmail}} sobre la cuenta de un menor, el acceso a los datos o su eliminación. Solo pedimos la información necesaria para identificar la cuenta y comprobar la facultad de actuar en su nombre. Cuando la legislación aplicable exige autorización parental, utilizar una cuenta Apple o seguir jugando no sustituye esa autorización.')] },
        { id: 'automated-decisions', heading: 'Emparejamiento y cálculos automáticos', blocks: [p('El juego calcula automáticamente puntuaciones, posiciones, desbloqueos y rivales adecuados a partir de los datos del juego y puede emparejarte con un rival controlado por el ordenador. Estas funciones del juego no toman decisiones que produzcan efectos jurídicos o que te afecten significativamente de modo similar en el sentido del artículo 22 del RGPD.')] },
        { id: 'changes', heading: 'Fecha y cambios', blocks: [p('Última actualización: {{noticeDate}}. Actualizamos este aviso cuando cambia el juego o el tratamiento de sus datos. La versión actual está disponible en la aplicación y en la página pública de privacidad. Los cambios importantes se explican antes de que comience el tratamiento modificado.')] },
      ],
    },
    support: {
      title: 'Asistencia y contacto',
      shortTitle: 'Asistencia',
      description: 'Ayuda con Knucklebones Neon, privacidad y cuentas.',
      intro: 'Contacta con nosotros para problemas del juego, ayuda con la cuenta o solicitudes de privacidad.',
      sections: [
        { id: 'contact', heading: 'Contacto', blocks: [p('Correo electrónico: {{publicEmail}}')] },
        { id: 'help', heading: 'En qué podemos ayudarte', blocks: [list('Problemas técnicos y de accesibilidad', 'Cuentas clasificatorias y apodos', 'Derechos de privacidad y eliminación de cuentas', 'Avisos sobre seguridad o usos indebidos', 'Consultas de madres, padres o tutores sobre la cuenta de un menor')] },
        { id: 'details', heading: 'Qué información incluir', blocks: [p('Describe lo ocurrido e indica la versión de la aplicación o del navegador. Incluye tu apodo o el correo confirmado de la cuenta solo si es necesario para localizarla. Elimina la información privada de otras personas de las capturas de pantalla.')] },
        { id: 'credentials', heading: 'Mantén tus credenciales en privado', blocks: [p('Nunca envíes tu contraseña, enlaces de inicio de sesión o recuperación, tokens de acceso, códigos de autorización de Apple ni datos privados de otra persona. No pedimos esas credenciales por correo electrónico.')] },
        { id: 'handling', heading: 'Cómo se tramitan las solicitudes', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Las solicitudes de derechos de privacidad previstos por la ley suelen responderse en el plazo de un mes; cualquier prórroga permitida y su motivo se explican dentro de ese plazo.')] },
      ],
    },
    'delete-account': {
      title: 'Eliminar tu cuenta',
      shortTitle: 'Eliminar cuenta',
      description: 'Cómo eliminar una cuenta clasificatoria de Knucklebones Neon dentro o fuera de la aplicación.',
      intro: 'La eliminación de tu cuenta clasificatoria es permanente. Puedes seguir jugando en local sin ella.',
      sections: [
        { id: 'in-app', heading: 'Eliminar desde la aplicación', blocks: [list('Abre tu perfil desde Inicio.', 'Abre los controles de la cuenta.', 'Elige Eliminar cuenta y lee la explicación.', 'Confirma la eliminación permanente.')] },
        { id: 'server-data', heading: 'Qué se elimina', blocks: [p('El juego resuelve cualquier partida activa y elimina tu cuenta alojada, perfil, ajustes, entradas en la cola y en la clasificación, historial de partidas y movimientos, runas y progreso. Esa identidad clasificatoria y sus resultados no pueden restaurarse desde la aplicación.')] },
        { id: 'local-data', heading: 'Datos sin conexión en tu dispositivo', blocks: [p('La eliminación de la cuenta cierra tu sesión y borra la sesión local de la cuenta y el perfil en caché. Tus ajustes sin conexión, estadísticas y archivos del juego en caché permanecen. Para borrarlos también, elimina los datos de este sitio en el navegador. En Android, borra el almacenamiento o los datos de la aplicación en los ajustes del dispositivo. En iOS, elimina la aplicación; desinstalarla sin eliminar sus datos conserva sus documentos y datos. Borrar solo los datos del dispositivo no elimina la cuenta del servidor.')] },
        { id: 'external', heading: 'Solicitar la eliminación sin la aplicación', blocks: [p('Escribe a {{publicEmail}} e indica que quieres eliminar tu cuenta clasificatoria de Knucklebones Neon. Usa el correo confirmado de la cuenta si todavía tienes acceso a él. Incluye un apodo solo si es necesario para localizar la cuenta. No envíes credenciales de inicio de sesión. Una madre, un padre o un tutor también puede contactar con nosotros sobre la cuenta de un menor.')] },
        { id: 'verification', heading: 'Comprobaciones de titularidad y copias restantes', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Una cuenta vinculada a Apple', blocks: [p('La eliminación también intenta revocar la conexión de Iniciar sesión con Apple. Los fallos transitorios se reintentan durante un máximo de {{appleRevocationRetryDays}} días. Si la revocación automática no puede completarse, sigue las instrucciones de la aplicación o elimina la conexión de la aplicación en los ajustes de tu cuenta Apple. Esto no elimina tu cuenta Apple. Tampoco se elimina tu cuenta independiente de Game Center.')] },
      ],
    },
  },
};
