import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const FR_LEGAL: LegalLocaleContent = {
  siteTitle: 'Informations légales de Knucklebones Neon',
  languageLabel: 'Langue',
  pageNavigationLabel: 'Informations légales',
  languageNavigationLabel: 'Langues disponibles',
  homeLabel: 'Retour au jeu',
  backLabel: 'Retour',
  pendingFact: 'Vérification requise avant publication',
  pages: {
    imprint: {
      title: 'Informations sur le responsable',
      shortTitle: 'Mentions légales',
      description: 'Identité et coordonnées du responsable de Knucklebones Neon.',
      intro: 'La personne physique ci-dessous est responsable de Knucklebones Neon.',
      sections: [
        { id: 'provider', heading: 'Responsable au titre de l’article 18(1) MStV', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'Contact', blocks: [p('E-mail : {{publicEmail}}')] },
        { id: 'project', heading: 'À propos de ce projet', blocks: [p('Knucklebones Neon est un jeu gratuit développé comme loisir, sans but commercial. Il ne comporte ni publicité, ni achats, ni abonnements, ni dons.')] },
      ],
    },
    privacy: {
      title: 'Avis de confidentialité',
      shortTitle: 'Confidentialité',
      description: 'Comment Knucklebones Neon traite les données de l’appareil, du compte et du jeu en ligne.',
      intro: 'Vous pouvez jouer en local sans compte de jeu classé. Le jeu en ligne nécessite un compte pour enregistrer votre progression et trouver des adversaires. Cet avis explique quelles données sont utilisées, qui les reçoit et comment les supprimer.',
      sections: [
        { id: 'controller', heading: 'Qui est responsable', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Pour toute question ou demande concernant la confidentialité, écrivez à {{publicEmail}}.')] },
        { id: 'scope', heading: 'Champ d’application de cet avis', blocks: [p('Cet avis couvre le site web, l’application web installée, le jeu autonome, le widget intégré et les applications natives Knucklebones Neon. Cloudflare distribue le site web et ses fichiers. Les applications natives chargent les fichiers du jeu depuis le paquet installé, mais les fonctions en ligne contactent toujours leurs prestataires de services. Si vous utilisez un widget sur un autre site web, ce site peut également traiter des données selon son propre avis de confidentialité.'), p('Nous n’intégrons ni publicité, ni analyse comportementale, ni SDK de suivi. Le jeu ne demande pas votre position, vos contacts, l’accès à votre appareil photo ou à vos photos. Il ne propose ni discussion entre joueurs ni envoi d’images. Les données opérationnelles et de sécurité traitées par nos fournisseurs d’infrastructure sont décrites ci-dessous.')] },
        { id: 'device-storage', heading: 'Données stockées sur votre appareil', blocks: [p('Le navigateur ou l’application conserve la langue choisie, les réglages d’accessibilité et du jeu, ainsi que les scores et statistiques locaux. Pour les comptes en ligne, il conserve aussi les données d’authentification de session et des copies locales de votre profil, des informations sur les comptes liés, des parties récentes, des runes et de la progression. Ces copies du compte sont également conservées sur le serveur ; ces données ne sont pas exclusivement locales.'), p('L’application web met les fichiers du jeu en cache pour fonctionner hors ligne. Elle conserve aussi brièvement un indicateur de récupération lorsqu’un fichier du programme ne se charge pas. Ces usages comprennent le stockage local du navigateur, le stockage de session et le cache de fichiers de l’application ; il ne s’agit pas de cookies publicitaires.'), p('Le stockage et l’accès nécessaires pour fournir une fonction que vous demandez reposent sur l’article 25(2)(2) TDDDG. Le traitement de données personnelles lié à ces fonctions suit les finalités et bases juridiques ci-dessous. Pour supprimer les données locales, suivez les étapes propres à votre appareil dans Supprimer votre compte. Effacer une session invitée sans moyen de récupération peut vous empêcher d’accéder de nouveau à ce compte.')] },
        { id: 'accounts', heading: 'Comptes invités, e-mail et progression', blocks: [p('Lorsque vous demandez à jouer en mode classé, le jeu utilise ou restaure votre compte existant. Lorsque cela est possible sur iOS, il utilise votre identité Game Center liée. Sinon, il crée un compte invité sans demander votre nom ni votre adresse e-mail. « Invité » ne signifie pas que les données sont anonymes : le compte possède un identifiant persistant.'), p('Les données du compte comprennent l’identifiant, un pseudonyme généré ou choisi, un avatar prédéfini, les réglages, les points actuels et leur maximum atteint, les résultats classés, les victoires, les défaites, les séries, la date et l’heure de création du profil, les parties et les coups joués. Les runes, contenus débloqués, succès, défis hebdomadaires et autres éléments de progression sont également enregistrés.'), p('L’inscription, la connexion et la récupération par e-mail et mot de passe sont facultatives. Supabase Auth traite l’adresse e-mail et les données d’authentification par mot de passe pour ces fonctions. {{smtpProvider}} achemine les messages de confirmation et de récupération du compte. Vous pouvez jouer en tant qu’invité sans fournir d’adresse e-mail, mais les possibilités de récupération sont alors limitées. Les données nécessaires du compte en ligne et des coups joués ne peuvent pas être omises si vous utilisez le jeu classé.')] },
        { id: 'apple', heading: 'Se connecter avec Apple et Game Center', blocks: [p('Sur iOS, l’authentification Game Center est initialisée au démarrage de l’application. Apple peut donc traiter des données Game Center avant le début d’une partie classée. Le jeu utilise l’état d’authentification Apple et un identifiant de joueur propre à l’équipe de développement pour restaurer ou lier votre compte de jeu classé et le protéger lorsque le compte Game Center de l’appareil change. Les données de vérification signées transitent par une passerelle Cloudflare vers Supabase. Cette intégration ne nous transmet ni vos amis Game Center, ni votre photo de profil, ni votre nom de profil public.'), p('Si vous choisissez Se connecter avec Apple, Apple fournit un identifiant de compte, des données d’authentification signées et, lorsqu’elle est transmise, votre véritable adresse e-mail ou l’adresse du relais privé d’Apple. Un code d’autorisation est échangé pour permettre une révocation ultérieure. Le justificatif de renouvellement obtenu est chiffré dans Supabase Vault et utilisé uniquement pour révoquer la connexion Apple lorsque vous supprimez le compte.'), p('Apple exploite ses services de compte et Game Center selon ses propres conditions et informations de confidentialité : https://www.apple.com/legal/privacy/ et https://www.apple.com/legal/privacy/data/en/game-center/. Vous gérez Game Center dans les réglages de votre appareil Apple.')] },
        { id: 'purposes', heading: 'Pourquoi nous traitons les données et sur quelles bases', blocks: [p('Nous traitons les données nécessaires au jeu gratuit demandé, à l’accès au compte et à sa récupération, à la progression enregistrée, à la recherche d’adversaires, à la validation des parties et aux résultats classés sur la base d’intérêts légitimes (article 6(1)(f) du RGPD). Nos intérêts sont de fournir les fonctions que vous choisissez, de préserver votre progression et de proposer un jeu équitable et fiable. Les informations publiques du profil se limitent aux données du jeu décrites ci-dessous ; nous n’avons pas besoin de votre vrai nom.'), p('Nous traitons également les données de requête et de sécurité nécessaires, telles que les adresses IP, les heures des requêtes, les informations du navigateur ou de l’application, les statuts des réponses et les informations d’erreur, pour fournir le service, prévenir les abus, limiter les requêtes excessives et rechercher les causes des dysfonctionnements (article 6(1)(f) du RGPD). Pour les demandes d’exercice des droits en matière de protection des données, le traitement nécessaire au respect de nos obligations repose sur l’article 6(1)(c), conjointement avec les articles 12 à 22 du RGPD.')] },
        { id: 'recipients', heading: 'Prestataires et traitement international', blocks: [p('Supabase fournit l’authentification hébergée, la base de données, les connexions de jeu en temps réel et les fonctions serveur. Région de la base de données : {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Les e-mails de compte sont envoyés par {{smtpProvider}}. Apple traite aussi des données pour les services Apple décrits ci-dessus. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'Ce que les autres personnes peuvent voir', blocks: [p('En jouant des parties classées, vous participez à un classement public. Votre pseudonyme, votre avatar prédéfini, vos points actuels et leur maximum atteint, votre rang ou votre statut au sommet du classement, vos victoires, défaites, parties jouées, meilleure série, date d’inscription et résultats classés peuvent apparaître dans le classement et les fiches de joueur. Ces résumés publics du profil sont aussi consultables sans connexion à un compte. Choisissez un pseudonyme qui ne révèle ni votre vrai nom ni vos coordonnées.'), p('Votre adresse e-mail, vos données d’authentification par mot de passe et vos données d’authentification Apple ne sont pas publiques. L’historique détaillé du compte n’est visible que par son titulaire ; les deux participants peuvent accéder à l’historique de leur partie commune et des coups joués.')] },
        { id: 'retention', heading: 'Durée de conservation des données', blocks: [p('Les comptes invités et les comptes récupérables n’expirent actuellement pas automatiquement en cas d’inactivité. Les données du compte et du jeu restent conservées jusqu’à la suppression du compte. La suppression règle toute partie active et efface le compte, le profil, les réglages, les inscriptions dans la file d’attente et le classement, l’historique des parties et des coups, les runes et la progression. Les enregistrements techniques utilisés pour empêcher les commandes de jeu en double deviennent éligibles au nettoyage exécuté toutes les heures lorsque leur création et la fin de la partie correspondante remontent toutes deux à plus de {{commandReceiptRetentionDays}} jours.'), p('Après la suppression d’un compte lié à Apple, toute donnée d’authentification encore nécessaire à la révocation automatique est conservée sous forme chiffrée pendant une période de nouvelles tentatives allant jusqu’à {{appleRevocationRetryDays}} jours, puis supprimée par le traitement planifié. Le traitement planifié s’exécute toutes les {{appleRevocationScheduleMinutes}} minutes ; les nouvelles tentatives individuelles peuvent avoir lieu plus tard. Si la révocation ne peut pas aboutir automatiquement, suivez les instructions manuelles décrites dans Supprimer votre compte.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('Les réglages locaux hors ligne, les statistiques et les fichiers du jeu en cache restent sur l’appareil jusqu’à ce que vous effaciez les données de l’application ou du site dans le navigateur. La seule suppression du compte serveur ne supprime pas ces éléments hors ligne.')] },
        { id: 'support', heading: 'Assistance et demandes de confidentialité', blocks: [p('Si vous nous contactez, nous traitons votre adresse d’expéditeur, votre message et les informations que vous choisissez d’inclure, comme la version de l’application, votre pseudonyme ou une capture d’écran. Nous utilisons uniquement ce qui est nécessaire pour répondre à votre question ou examiner le problème signalé (article 6(1)(f) du RGPD) ; la base juridique des demandes d’exercice de droits prévus par la loi est décrite ci-dessus. N’envoyez pas de mots de passe ni de liens d’authentification.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'Vos droits', blocks: [p('Sous réserve des conditions légales applicables, vous pouvez demander l’accès à vos données personnelles, leur rectification, leur effacement ou la limitation du traitement. La portabilité des données s’applique lorsque le traitement est automatisé et repose sur le consentement ou un contrat. Si le traitement repose sur le consentement, vous pouvez le retirer pour l’avenir sans remettre en cause la licéité du traitement antérieur.'), p('Contactez {{publicEmail}}. Nous répondons normalement dans les meilleurs délais et dans un délai d’un mois. Si une prolongation autorisée par la loi est nécessaire, nous en expliquons le motif au cours de ce premier mois. {{deletionVerification}}'), p('Vous pouvez déposer une réclamation auprès d’une autorité de protection des données, notamment celle du lieu où vous résidez, travaillez ou estimez qu’une violation a eu lieu. L’autorité compétente pour ce responsable est {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Informations et contact pour les réclamations : https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'Votre droit d’opposition', blocks: [p('Lorsque le traitement repose sur l’article 6(1)(f) du RGPD, vous pouvez vous y opposer à tout moment pour des raisons tenant à votre situation particulière. Écrivez à {{publicEmail}}. Nous cesserons ce traitement, sauf si nous pouvons démontrer des motifs légitimes et impérieux qui prévalent sur vos intérêts, droits et libertés, ou si le traitement est nécessaire à la constatation, à l’exercice ou à la défense de droits en justice.')] },
        { id: 'children', heading: 'Enfants et parents', blocks: [p('Knucklebones Neon est un jeu destiné au grand public. Il ne pose pas de question sur l’âge et ne demande pas de date de naissance. Le jeu local ne nécessite pas de compte de jeu classé. Le jeu en ligne conserve les informations du compte et du jeu décrites ici, y compris celles des joueurs plus jeunes.'), p('Si tu es jeune : utilise un pseudonyme inventé, garde ton mot de passe secret et demande de l’aide à un adulte de confiance pour les questions de compte ou de confidentialité. D’autres personnes peuvent voir ton pseudonyme et tes résultats. Ce jeu ne comporte ni discussion entre joueurs, ni publicité, ni paiement.'), p('Les parents et représentants légaux peuvent contacter {{publicEmail}} au sujet du compte d’un enfant, de l’accès aux données ou de leur suppression. Nous demandons uniquement les informations nécessaires pour identifier le compte et vérifier l’autorité à agir. Lorsque la loi applicable exige une autorisation parentale, l’utilisation d’un compte Apple ou la poursuite du jeu ne remplace pas cette autorisation.')] },
        { id: 'automated-decisions', heading: 'Recherche d’adversaires et calculs automatiques', blocks: [p('Le jeu calcule automatiquement les scores, les rangs, les déblocages et les adversaires appropriés à partir des données du jeu, et peut vous opposer à un adversaire contrôlé par l’ordinateur. Ces fonctions du jeu ne prennent pas de décisions produisant des effets juridiques ou vous affectant de manière significative de façon similaire au sens de l’article 22 du RGPD.')] },
        { id: 'changes', heading: 'Date et modifications', blocks: [p('Dernière mise à jour : {{noticeDate}}. Nous mettons cet avis à jour lorsque le jeu ou le traitement de ses données change. La version actuelle est disponible dans l’application et sur la page publique de confidentialité. Les changements importants sont expliqués avant le début du traitement modifié.')] },
      ],
    },
    support: {
      title: 'Assistance et contact',
      shortTitle: 'Assistance',
      description: 'Aide concernant Knucklebones Neon, la confidentialité et les comptes.',
      intro: 'Contactez-nous pour un problème de jeu, une aide concernant votre compte ou une demande de confidentialité.',
      sections: [
        { id: 'contact', heading: 'Contact', blocks: [p('E-mail : {{publicEmail}}')] },
        { id: 'help', heading: 'Comment nous pouvons vous aider', blocks: [list('Problèmes techniques et d’accessibilité', 'Comptes de jeu classé et pseudonymes', 'Droits en matière de protection des données et suppression du compte', 'Signalements de sécurité ou d’abus', 'Questions des parents sur le compte d’un enfant')] },
        { id: 'details', heading: 'Informations à inclure', blocks: [p('Décrivez ce qui s’est passé et indiquez la version de l’application ou du navigateur. Indiquez votre pseudonyme ou l’adresse e-mail confirmée du compte uniquement si cela est nécessaire pour le retrouver. Retirez les informations privées d’autres personnes des captures d’écran.')] },
        { id: 'credentials', heading: 'Gardez vos données d’authentification secrètes', blocks: [p('N’envoyez jamais votre mot de passe, un lien de connexion ou de récupération, un jeton d’accès, un code d’autorisation Apple ou les données privées d’une autre personne. Nous ne demandons pas ces données d’authentification par e-mail.')] },
        { id: 'handling', heading: 'Traitement des demandes', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Les demandes d’exercice des droits de confidentialité prévus par la loi reçoivent normalement une réponse dans un délai d’un mois ; toute prolongation autorisée et son motif sont expliqués dans ce délai.')] },
      ],
    },
    'delete-account': {
      title: 'Supprimer votre compte',
      shortTitle: 'Suppression',
      description: 'Comment supprimer un compte de jeu classé Knucklebones Neon dans l’application ou en dehors de celle-ci.',
      intro: 'La suppression de votre compte de jeu classé est définitive. Vous pouvez continuer à jouer en local sans ce compte.',
      sections: [
        { id: 'in-app', heading: 'Supprimer dans l’application', blocks: [list('Ouvrez votre profil depuis l’accueil.', 'Ouvrez les commandes du compte.', 'Choisissez Supprimer le compte et lisez l’explication.', 'Confirmez la suppression définitive.')] },
        { id: 'server-data', heading: 'Ce qui est supprimé', blocks: [p('Le jeu règle toute partie active et supprime votre compte hébergé, votre profil, vos réglages, vos inscriptions dans la file d’attente et le classement, l’historique des parties et des coups, les runes et la progression. Cette identité de jeu classé et ses résultats ne peuvent pas être restaurés depuis l’application.')] },
        { id: 'local-data', heading: 'Données hors ligne sur votre appareil', blocks: [p('La suppression du compte vous déconnecte et efface la session locale du compte ainsi que le profil en cache. Vos réglages hors ligne, statistiques et fichiers du jeu en cache restent sur l’appareil. Pour les supprimer aussi, effacez les données de ce site dans le navigateur. Sur Android, effacez le stockage ou les données de l’application dans les réglages de l’appareil. Sur iOS, supprimez l’application ; la décharger conserve ses documents et données. Effacer seulement les données de l’appareil ne supprime pas le compte serveur.')] },
        { id: 'external', heading: 'Demander la suppression sans l’application', blocks: [p('Écrivez à {{publicEmail}} en précisant que vous souhaitez supprimer votre compte de jeu classé Knucklebones Neon. Utilisez l’adresse e-mail confirmée du compte si vous y avez encore accès. Indiquez un pseudonyme uniquement si cela est nécessaire pour retrouver le compte. N’envoyez pas de données d’authentification. Un parent ou représentant légal peut également nous contacter au sujet du compte d’un enfant.')] },
        { id: 'verification', heading: 'Vérification du titulaire et copies restantes', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Compte lié à Apple', blocks: [p('La suppression tente aussi de révoquer la connexion Se connecter avec Apple. En cas d’échec temporaire, de nouvelles tentatives sont effectuées pendant {{appleRevocationRetryDays}} jours au maximum. Si la révocation automatique ne peut pas aboutir, suivez les instructions dans l’application ou supprimez la connexion de l’application dans les réglages de votre compte Apple. Cela ne supprime pas votre compte Apple. Votre compte Game Center distinct n’est pas supprimé non plus.')] },
      ],
    },
  },
};
