import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const IT_LEGAL: LegalLocaleContent = {
  siteTitle: 'Informazioni legali di Knucklebones Neon',
  languageLabel: 'Lingua',
  pageNavigationLabel: 'Informazioni legali',
  languageNavigationLabel: 'Lingue disponibili',
  homeLabel: 'Torna al gioco',
  backLabel: 'Indietro',
  pendingFact: 'In attesa di verifica prima della pubblicazione',
  pages: {
    imprint: {
      title: 'Informazioni sul responsabile',
      shortTitle: 'Note legali',
      description: 'Informazioni sul responsabile e contatti di Knucklebones Neon.',
      intro: 'La persona fisica indicata di seguito è responsabile di Knucklebones Neon.',
      sections: [
        { id: 'provider', heading: 'Responsabile ai sensi del § 18(1) MStV', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'Contatto', blocks: [p('E-mail: {{publicEmail}}')] },
        { id: 'project', heading: 'Informazioni sul progetto', blocks: [p('Knucklebones Neon è un gioco gratuito sviluppato per hobby, senza finalità commerciali. Non contiene pubblicità, acquisti, abbonamenti né donazioni.')] },
      ],
    },
    privacy: {
      title: 'Informativa sulla privacy',
      shortTitle: 'Privacy',
      description: 'Come Knucklebones Neon tratta i dati del dispositivo, dell’account e del gioco online.',
      intro: 'Puoi giocare in locale senza un account per le partite classificate. Per giocare online serve un account che consenta di salvare i progressi e trovare avversari. Questa informativa spiega quali dati vengono usati, chi li riceve e come puoi eliminarli.',
      sections: [
        { id: 'controller', heading: 'Chi è il titolare del trattamento', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Per domande o richieste sulla privacy, scrivi a {{publicEmail}}.')] },
        { id: 'scope', heading: 'Ambito di questa informativa', blocks: [p('Questa informativa riguarda il sito web, l’app web installata, il gioco autonomo, il widget incorporato e le app native di Knucklebones Neon. Cloudflare distribuisce il sito web e i suoi file. Le app native caricano i file del gioco dal pacchetto installato, ma le funzioni online continuano a contattare i rispettivi fornitori di servizi. Se giochi tramite un widget su un altro sito web, quel sito può a sua volta trattare dati secondo la propria informativa sulla privacy.'), p('Non integriamo pubblicità, analisi comportamentali o SDK di tracciamento. Il gioco non richiede la tua posizione, i contatti, l’accesso alla fotocamera o alle foto e non offre chat tra giocatori né caricamento di immagini. I dati operativi e di sicurezza trattati dai nostri fornitori di infrastruttura sono descritti di seguito.')] },
        { id: 'device-storage', heading: 'Dati memorizzati sul tuo dispositivo', blocks: [p('Il browser o l’app memorizza la lingua scelta, le impostazioni di accessibilità e di gioco, i punteggi e le statistiche locali. Per gli account online memorizza anche le credenziali di sessione e copie locali del profilo, delle informazioni sugli account collegati, delle partite recenti, delle rune e dei progressi. Queste copie dell’account sono conservate anche sul server; non si tratta di dati esclusivamente locali.'), p('L’app web conserva nella cache i file del gioco per funzionare offline. Memorizza inoltre per breve tempo un indicatore di ripristino quando un file del programma non viene caricato. Questi usi comprendono l’archiviazione locale del browser, l’archiviazione di sessione e la cache dei file dell’app; non si tratta di cookie pubblicitari.'), p('La memorizzazione e l’accesso necessari a fornire una funzione da te richiesta si basano sul § 25(2)(2) TDDDG. Il trattamento dei dati personali per queste funzioni segue le finalità e le basi giuridiche indicate di seguito. Per rimuovere i dati locali, segui le istruzioni specifiche per il tuo dispositivo in Elimina account. Cancellare una sessione ospite senza possibilità di recupero può impedirti di accedere nuovamente a quell’account.')] },
        { id: 'accounts', heading: 'Account ospite, e-mail e progressi di gioco', blocks: [p('Quando richiedi una partita classificata, il gioco usa o ripristina il tuo account esistente. Su iOS, quando possibile, usa la tua identità Game Center collegata. Altrimenti crea un account ospite senza chiedere il nome o l’indirizzo e-mail. “Ospite” non significa che i dati siano anonimi: l’account ha un identificativo persistente.'), p('I dati dell’account comprendono l’identificativo, un nickname generato o scelto, un avatar predefinito, le impostazioni, i punti attuali e il massimo raggiunto, i risultati classificati, le vittorie, le sconfitte, le serie, la data e l’ora di creazione del profilo, le partite e le mosse. Vengono salvati anche rune, contenuti sbloccati, obiettivi, sfide settimanali e altri progressi.'), p('La registrazione, l’accesso e il recupero tramite e-mail e password sono facoltativi. Supabase Auth tratta l’indirizzo e-mail e le credenziali della password per queste funzioni. {{smtpProvider}} recapita i messaggi di conferma e recupero dell’account. Puoi giocare come ospite senza fornire un’e-mail, ma le possibilità di recupero sono allora limitate. I dati necessari dell’account online e delle mosse non possono essere omessi durante l’uso delle partite classificate.')] },
        { id: 'apple', heading: 'Accedi con Apple e Game Center', blocks: [p('Su iOS, l’autenticazione di Game Center viene inizializzata all’avvio dell’app. Apple può quindi trattare dati di Game Center prima che tu avvii una partita classificata. Il gioco usa lo stato di autenticazione Apple e un identificativo del giocatore specifico del team di sviluppo per ripristinare o collegare il tuo account per le partite classificate e proteggerlo quando cambia l’account Game Center del dispositivo. I dati di verifica firmati passano attraverso un gateway Cloudflare per raggiungere Supabase. Questa integrazione non ci fornisce i tuoi amici, la foto del profilo o il nome pubblico del profilo Game Center.'), p('Se scegli Accedi con Apple, Apple fornisce un identificativo dell’account, dati di autenticazione firmati e, quando trasmesso, il tuo indirizzo e-mail reale o l’indirizzo di inoltro privato di Apple. Un codice di autorizzazione viene scambiato per consentire una successiva revoca. La credenziale di aggiornamento risultante viene cifrata in Supabase Vault e usata soltanto per revocare il collegamento con Apple quando elimini l’account.'), p('Apple gestisce i propri servizi di account e Game Center secondo le proprie condizioni e informazioni sulla privacy: https://www.apple.com/legal/privacy/ e https://www.apple.com/legal/privacy/data/en/game-center/. Puoi gestire Game Center nelle impostazioni del tuo dispositivo Apple.')] },
        { id: 'purposes', heading: 'Perché trattiamo i dati e su quali basi giuridiche', blocks: [p('Trattiamo i dati necessari per il gioco gratuito richiesto, l’accesso e il recupero dell’account, i progressi salvati, l’abbinamento degli avversari, la convalida delle partite e i risultati classificati sulla base di interessi legittimi (articolo 6(1)(f) GDPR). I nostri interessi sono fornire le funzioni che scegli, preservare i tuoi progressi e gestire un gioco equo e affidabile. Le informazioni pubbliche del profilo sono limitate ai dati di gioco descritti di seguito; non abbiamo bisogno del tuo vero nome.'), p('Trattiamo inoltre i dati necessari relativi alle richieste e alla sicurezza, come indirizzi IP, orari delle richieste, informazioni del browser o dell’app, stato delle risposte e informazioni sugli errori, per fornire il servizio, prevenire abusi, limitare le richieste eccessive e indagare sui malfunzionamenti (articolo 6(1)(f) GDPR). Per le richieste di esercizio dei diritti in materia di privacy, il trattamento necessario ad adempiere ai nostri obblighi si basa sull’articolo 6(1)(c) in combinato disposto con gli articoli da 12 a 22 GDPR.')] },
        { id: 'recipients', heading: 'Fornitori di servizi e trattamento internazionale', blocks: [p('Supabase fornisce autenticazione ospitata, database, connessioni di gioco in tempo reale e funzioni server. Regione del database: {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Le e-mail dell’account vengono inviate tramite {{smtpProvider}}. Apple tratta inoltre dati per i servizi Apple descritti sopra. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'Cosa possono vedere le altre persone', blocks: [p('Giocando partite classificate, partecipi a una classifica pubblica. Il tuo nickname, l’avatar predefinito, i punti attuali e il massimo raggiunto, la posizione o lo status al vertice della classifica, le vittorie, le sconfitte, le partite giocate, la serie migliore, la data di iscrizione e i risultati classificati possono essere mostrati nella classifica e nelle schede giocatore. Questi riepiloghi pubblici del profilo possono essere consultati anche senza aver effettuato l’accesso a un account. Scegli un nickname che non riveli il tuo vero nome o i tuoi recapiti.'), p('La tua e-mail, le credenziali della password e i dati di autenticazione Apple non sono pubblici. La cronologia dettagliata dell’account è visibile solo al titolare; i due partecipanti possono accedere alla cronologia della partita e delle mosse che hanno condiviso.')] },
        { id: 'retention', heading: 'Per quanto tempo conserviamo i dati', blocks: [p('Al momento, gli account ospite e gli account recuperabili non scadono automaticamente per inattività. I dati dell’account e del gioco rimangono fino all’eliminazione dell’account. L’eliminazione risolve eventuali partite attive e rimuove l’account, il profilo, le impostazioni, le voci nella coda e nella classifica, la cronologia delle partite e delle mosse, le rune e i progressi. Le registrazioni tecniche usate per impedire comandi di gioco duplicati possono essere rimosse dalla pulizia eseguita ogni ora quando sia la loro creazione sia la fine della partita corrispondente risalgono a più di {{commandReceiptRetentionDays}} giorni prima.'), p('Dopo l’eliminazione di un account collegato ad Apple, qualsiasi credenziale ancora necessaria alla revoca automatica viene conservata cifrata durante un periodo di nuovi tentativi fino a {{appleRevocationRetryDays}} giorni e poi rimossa dall’elaborazione pianificata. L’elaborazione pianificata viene eseguita ogni {{appleRevocationScheduleMinutes}} minuti; i singoli nuovi tentativi possono avvenire più tardi. Se la revoca non può essere completata automaticamente, usa le istruzioni manuali descritte in Elimina account.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('Le impostazioni locali offline, le statistiche e i file del gioco nella cache rimangono finché non cancelli i dati dell’app o del sito nel browser. La sola eliminazione dell’account sul server non rimuove questi elementi offline.')] },
        { id: 'support', heading: 'Assistenza e richieste sulla privacy', blocks: [p('Se ci contatti, trattiamo il tuo indirizzo di mittente, il messaggio e le informazioni che scegli di includere, come la versione dell’app, il nickname o uno screenshot. Usiamo soltanto quanto necessario per rispondere alla tua domanda o indagare sul problema segnalato (articolo 6(1)(f) GDPR); la base giuridica delle richieste di esercizio dei diritti previsti dalla legge è descritta sopra. Non inviare password o link di autenticazione.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'I tuoi diritti', blocks: [p('Nel rispetto delle condizioni di legge applicabili, puoi richiedere l’accesso ai tuoi dati personali, la rettifica, la cancellazione o la limitazione del trattamento. La portabilità dei dati si applica quando il trattamento è automatizzato e si basa sul consenso o su un contratto. Se il trattamento si basa sul consenso, puoi revocarlo per il futuro senza pregiudicare la liceità del trattamento precedente.'), p('Contatta {{publicEmail}}. Normalmente rispondiamo senza ingiustificato ritardo ed entro un mese. Se è necessaria una proroga consentita dalla legge, ne spieghiamo il motivo entro quel primo mese. {{deletionVerification}}'), p('Puoi presentare un reclamo a un’autorità di protezione dei dati, inclusa quella del luogo in cui risiedi, lavori o ritieni che si sia verificata una violazione. L’autorità competente per questo titolare è {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Informazioni e contatti per i reclami: https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'Il tuo diritto di opposizione', blocks: [p('Quando il trattamento si basa sull’articolo 6(1)(f) GDPR, puoi opporti in qualsiasi momento per motivi connessi alla tua situazione particolare. Scrivi a {{publicEmail}}. Interromperemo quel trattamento, salvo che possiamo dimostrare motivi legittimi cogenti che prevalgano sui tuoi interessi, diritti e libertà, oppure che il trattamento sia necessario per accertare, esercitare o difendere un diritto in sede giudiziaria.')] },
        { id: 'children', heading: 'Minori e genitori', blocks: [p('Knucklebones Neon è un gioco rivolto al pubblico generale. Non pone domande sull’età e non chiede la data di nascita. Il gioco locale non richiede un account per le partite classificate. Il gioco online conserva invece le informazioni dell’account e del gioco descritte qui, comprese quelle dei giocatori più giovani.'), p('Se sei giovane: usa un nickname inventato, mantieni segreta la password e chiedi aiuto a un adulto di fiducia per domande sull’account o sulla privacy. Le altre persone possono vedere il tuo nickname e i risultati delle tue partite. Questo gioco non ha chat tra giocatori, pubblicità o pagamenti.'), p('Genitori e tutori possono contattare {{publicEmail}} per l’account di un minore, l’accesso ai dati o la loro cancellazione. Chiediamo soltanto le informazioni necessarie per identificare l’account e verificare il diritto di agire. Quando la legge applicabile richiede l’autorizzazione dei genitori, usare un account Apple o continuare a giocare non sostituisce tale autorizzazione.')] },
        { id: 'automated-decisions', heading: 'Abbinamento e calcoli automatici', blocks: [p('Il gioco calcola automaticamente punteggi, posizioni, sblocchi e avversari adatti a partire dai dati di gioco e può abbinarti a un avversario controllato dal computer. Queste funzioni di gioco non prendono decisioni che producano effetti giuridici o incidano su di te in modo analogamente significativo ai sensi dell’articolo 22 GDPR.')] },
        { id: 'changes', heading: 'Data e modifiche', blocks: [p('Ultimo aggiornamento: {{noticeDate}}. Aggiorniamo questa informativa quando cambia il gioco o il trattamento dei suoi dati. La versione attuale è disponibile nell’app e sulla pagina pubblica della privacy. Le modifiche sostanziali vengono spiegate prima dell’inizio del trattamento modificato.')] },
      ],
    },
    support: {
      title: 'Assistenza e contatti',
      shortTitle: 'Assistenza',
      description: 'Aiuto con Knucklebones Neon, privacy e account.',
      intro: 'Contattaci per problemi con il gioco, assistenza per l’account o richieste sulla privacy.',
      sections: [
        { id: 'contact', heading: 'Contatto', blocks: [p('E-mail: {{publicEmail}}')] },
        { id: 'help', heading: 'Come possiamo aiutarti', blocks: [list('Problemi tecnici e di accessibilità', 'Account per partite classificate e nickname', 'Diritti in materia di privacy ed eliminazione dell’account', 'Segnalazioni di sicurezza o abusi', 'Domande dei genitori sull’account di un minore')] },
        { id: 'details', heading: 'Quali informazioni includere', blocks: [p('Descrivi cosa è successo e indica la versione dell’app o del browser. Includi il nickname o l’e-mail confermata dell’account solo se necessario per trovare l’account. Rimuovi dagli screenshot le informazioni private di altre persone.')] },
        { id: 'credentials', heading: 'Mantieni riservate le credenziali', blocks: [p('Non inviare mai la tua password, link di accesso o recupero, token di accesso, codici di autorizzazione Apple o dati privati di altre persone. Non chiediamo queste credenziali via e-mail.')] },
        { id: 'handling', heading: 'Come vengono gestite le richieste', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Le richieste di esercizio dei diritti in materia di privacy previsti dalla legge ricevono normalmente risposta entro un mese; eventuali proroghe consentite e i relativi motivi vengono spiegati entro quel termine.')] },
      ],
    },
    'delete-account': {
      title: 'Elimina il tuo account',
      shortTitle: 'Elimina account',
      description: 'Come eliminare un account per le partite classificate di Knucklebones Neon dentro o fuori dall’app.',
      intro: 'L’eliminazione del tuo account per le partite classificate è permanente. Puoi continuare a giocare in locale senza di esso.',
      sections: [
        { id: 'in-app', heading: 'Elimina dall’app', blocks: [list('Apri il tuo profilo dalla schermata iniziale.', 'Apri i controlli dell’account.', 'Scegli Elimina account e leggi la spiegazione.', 'Conferma l’eliminazione permanente.')] },
        { id: 'server-data', heading: 'Cosa viene eliminato', blocks: [p('Il gioco risolve eventuali partite attive ed elimina il tuo account ospitato, il profilo, le impostazioni, le voci nella coda e nella classifica, la cronologia delle partite e delle mosse, le rune e i progressi. Quell’identità nelle partite classificate e i suoi risultati non possono essere ripristinati tramite l’app.')] },
        { id: 'local-data', heading: 'Dati offline sul tuo dispositivo', blocks: [p('L’eliminazione dell’account ti disconnette e cancella la sessione locale dell’account e il profilo nella cache. Le impostazioni offline, le statistiche e i file del gioco nella cache rimangono. Per rimuovere anche questi, cancella i dati di questo sito nel browser. Su Android, cancella lo spazio di archiviazione o i dati dell’app nelle impostazioni del dispositivo. Su iOS, elimina l’app; disinstallarla senza eliminarne i dati conserva i suoi documenti e dati. Cancellare soltanto i dati del dispositivo non elimina l’account sul server.')] },
        { id: 'external', heading: 'Richiedi l’eliminazione senza l’app', blocks: [p('Scrivi a {{publicEmail}} e indica che vuoi eliminare il tuo account per le partite classificate di Knucklebones Neon. Usa l’e-mail confermata dell’account se puoi ancora accedervi. Includi un nickname solo se necessario per individuare l’account. Non inviare credenziali di accesso. Anche un genitore o tutore può contattarci per l’account di un minore.')] },
        { id: 'verification', heading: 'Verifica della titolarità e copie rimanenti', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Account collegato ad Apple', blocks: [p('L’eliminazione tenta anche di revocare il collegamento Accedi con Apple. In caso di errori temporanei, vengono effettuati nuovi tentativi per un massimo di {{appleRevocationRetryDays}} giorni. Se la revoca automatica non può essere completata, segui le istruzioni nell’app o rimuovi il collegamento dell’app nelle impostazioni del tuo account Apple. Questo non elimina il tuo account Apple. Non viene eliminato nemmeno il tuo account Game Center separato.')] },
      ],
    },
  },
};
