import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const PL_LEGAL: LegalLocaleContent = {
  siteTitle: 'Informacje prawne Knucklebones Neon',
  languageLabel: 'Język',
  pageNavigationLabel: 'Informacje prawne',
  languageNavigationLabel: 'Dostępne języki',
  homeLabel: 'Powrót do gry',
  backLabel: 'Wstecz',
  pendingFact: 'Do weryfikacji przed publikacją',
  pages: {
    imprint: {
      title: 'Informacje o usługodawcy',
      shortTitle: 'Nota prawna',
      description: 'Dane usługodawcy i kontakt do Knucklebones Neon.',
      intro: 'Usługodawcą Knucklebones Neon jest następująca osoba prywatna.',
      sections: [
        { id: 'provider', heading: 'Usługodawca zgodnie z § 18 ust. 1 MStV', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'Kontakt', blocks: [p('E-mail: {{publicEmail}}')] },
        { id: 'project', heading: 'O projekcie', blocks: [p('Knucklebones Neon to bezpłatna, niekomercyjna gra hobbystyczna. Nie zawiera reklam, zakupów, subskrypcji ani darowizn.')] },
      ],
    },
    privacy: {
      title: 'Informacja o prywatności',
      shortTitle: 'Prywatność',
      description: 'Jak Knucklebones Neon przetwarza dane urządzenia, konta i gry online.',
      intro: 'Możesz grać lokalnie bez konta rankingowego. Gra online wymaga konta, aby zapisywać postępy i dobierać przeciwników. Tutaj wyjaśniamy, jakie dane są używane, kto je otrzymuje i jak je usunąć.',
      sections: [
        { id: 'controller', heading: 'Kto odpowiada za dane', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Pytania i wnioski dotyczące prywatności kieruj na {{publicEmail}}.')] },
        { id: 'scope', heading: 'Zakres tej informacji', blocks: [p('Ta informacja obejmuje stronę internetową, zainstalowaną aplikację internetową, samodzielną grę, osadzany widżet i aplikacje natywne Knucklebones Neon. Cloudflare dostarcza stronę i jej pliki. Aplikacje natywne wczytują pliki gry z zainstalowanego pakietu, ale funkcje online nadal łączą się ze swoimi usługodawcami. Jeśli grasz w widżet na innej stronie, ta strona może również przetwarzać dane zgodnie z własną informacją o prywatności.'), p('Nie integrujemy reklam ani zestawów SDK do analityki behawioralnej lub śledzenia. Gra nie prosi o dostęp do lokalizacji, kontaktów, aparatu ani zdjęć; nie ma też czatu między graczami ani przesyłania obrazów. Dane operacyjne i bezpieczeństwa przetwarzane przez dostawców infrastruktury opisujemy poniżej.')] },
        { id: 'device-storage', heading: 'Dane zapisane na urządzeniu', blocks: [p('Przeglądarka lub aplikacja zapisuje wybrany język, ustawienia dostępności i gry oraz lokalne wyniki i statystyki. Dla kont online zapisuje także poświadczenia sesji i lokalne kopie profilu, informacji o połączonych kontach, ostatnich meczów, run i postępów. Te dane konta są również przechowywane na serwerze; nie są wyłącznie lokalne.'), p('Aplikacja internetowa zapisuje pliki gry w pamięci podręcznej, aby działać offline. Gdy plik programu nie zostanie wczytany, na krótko zapisuje też znacznik odzyskiwania. Wykorzystuje do tego pamięć lokalną przeglądarki, pamięć sesji i pamięć podręczną plików aplikacji; nie są to reklamowe pliki cookie.'), p('Zapisywanie i odczytywanie danych niezbędnych do udostępnienia wybranej przez Ciebie funkcji opiera się na § 25 ust. 2 pkt 2 TDDDG. Przetwarzanie danych osobowych na potrzeby tych funkcji odbywa się w celach i na podstawach prawnych opisanych poniżej. Aby usunąć dane lokalne, postępuj zgodnie z instrukcjami dla swojego urządzenia w części Usuń konto. Usunięcie sesji gościa, której nie można odzyskać, może uniemożliwić ponowny dostęp do tego konta.')] },
        { id: 'accounts', heading: 'Konta gości, e-mail i postępy', blocks: [p('Gdy wybierasz grę rankingową, gra korzysta z istniejącego konta lub je przywraca. W miarę możliwości na iOS używa powiązanej tożsamości Game Center. W innym przypadku tworzy konto gościa bez pytania o imię i nazwisko ani e-mail. „Gość” nie oznacza anonimowych danych: konto ma trwały identyfikator.'), p('Dane konta obejmują identyfikator, wygenerowany lub wybrany pseudonim, gotowy awatar, ustawienia, bieżące i najwyższe punkty, wyniki rankingowe, zwycięstwa, porażki, serie, czas utworzenia profilu, mecze i ruchy. Zapisywane są także runy, odblokowana zawartość, osiągnięcia, wyzwania tygodniowe i inne postępy.'), p('Rejestracja, logowanie i odzyskiwanie przy użyciu e-maila i hasła są opcjonalne. Supabase Auth przetwarza w tym celu adres e-mail i poświadczenia hasła. {{smtpProvider}} dostarcza wiadomości potwierdzające konto i umożliwiające odzyskanie dostępu. Możesz grać jako gość bez podawania e-maila, ale możliwości odzyskiwania są wtedy ograniczone. Gra rankingowa wymaga przetwarzania niezbędnych danych konta online i ruchów.')] },
        { id: 'apple', heading: 'Logowanie przez Apple i Game Center', blocks: [p('Na iOS uwierzytelnianie Game Center jest inicjowane przy uruchomieniu aplikacji. Apple może więc przetwarzać dane Game Center jeszcze przed rozpoczęciem meczu rankingowego. Gra używa stanu uwierzytelnienia Apple i identyfikatora gracza przypisanego do zespołu deweloperskiego, aby przywrócić lub połączyć konto rankingowe oraz chronić je po zmianie konta Game Center na urządzeniu. Podpisane dane weryfikacyjne trafiają do Supabase przez bramę Cloudflare. Ta integracja nie przekazuje nam listy znajomych, zdjęcia profilowego ani publicznej nazwy profilu Game Center.'), p('Jeśli wybierzesz logowanie przez Apple, Apple przekazuje identyfikator konta, podpisane dane uwierzytelniające oraz, jeśli go udostępni, rzeczywisty adres e-mail lub prywatny adres przekazujący Apple. Kod autoryzacji jest wymieniany, aby umożliwić późniejsze cofnięcie połączenia. Uzyskane poświadczenie odświeżania jest szyfrowane w Supabase Vault i służy wyłącznie do cofnięcia połączenia z Apple przy usunięciu konta.'), p('Apple świadczy usługi konta i Game Center na własnych warunkach i zgodnie z własnymi informacjami o prywatności: https://www.apple.com/legal/privacy/ oraz https://www.apple.com/legal/privacy/data/en/game-center/. Game Center możesz kontrolować w ustawieniach urządzenia Apple.')] },
        { id: 'purposes', heading: 'Cele i podstawy prawne przetwarzania', blocks: [p('Dane niezbędne do wybranej bezpłatnej gry, dostępu do konta i jego odzyskiwania, zapisywania postępów, dobierania przeciwników, weryfikacji gry i wyników rankingowych przetwarzamy na podstawie prawnie uzasadnionych interesów (art. 6 ust. 1 lit. f RODO). Nasze interesy to udostępnianie wybranych przez Ciebie funkcji, zachowanie postępów oraz prowadzenie uczciwej i niezawodnej gry. Publiczny profil ogranicza się do opisanych poniżej informacji o grze; nie potrzebujemy Twojego prawdziwego imienia i nazwiska.'), p('Przetwarzamy też niezbędne dane żądań i bezpieczeństwa, takie jak adresy IP, czas żądań, informacje o przeglądarce lub aplikacji, status odpowiedzi i informacje o błędach, aby dostarczać usługę, zapobiegać nadużyciom, ograniczać nadmierne żądania i badać usterki (art. 6 ust. 1 lit. f RODO). W przypadku wniosków dotyczących praw do ochrony danych przetwarzanie niezbędne do wypełnienia naszych obowiązków opiera się na art. 6 ust. 1 lit. c w związku z art. 12–22 RODO.')] },
        { id: 'recipients', heading: 'Usługodawcy i przetwarzanie międzynarodowe', blocks: [p('Supabase zapewnia hostowane uwierzytelnianie, bazę danych, połączenia gry w czasie rzeczywistym i funkcje serwerowe. Region bazy danych: {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Wiadomości dotyczące konta są wysyłane przez {{smtpProvider}}. Apple dodatkowo przetwarza dane na potrzeby opisanych wyżej usług Apple. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'Co mogą zobaczyć inne osoby', blocks: [p('Grając w mecze rankingowe, uczestniczysz w publicznym rankingu. Twój pseudonim, gotowy awatar, bieżące i najwyższe punkty, pozycja lub szczytowy status, zwycięstwa, porażki, liczba meczów, najlepsza seria, czas dołączenia i wyniki rankingowe mogą być widoczne w rankingu i na kartach graczy. Te publiczne podsumowania profili można pobrać również bez zalogowanego konta. Wybierz pseudonim, który nie ujawnia prawdziwego imienia i nazwiska ani danych kontaktowych.'), p('Twój e-mail, poświadczenia hasła i dane uwierzytelniania Apple nie są publiczne. Szczegółową historię konta widzi tylko jego właściciel; obaj uczestnicy meczu mogą uzyskać dostęp do wspólnej historii meczu i ruchów.')] },
        { id: 'retention', heading: 'Jak długo przechowujemy dane', blocks: [p('Konta gości i konta z możliwością odzyskania nie wygasają obecnie automatycznie z powodu nieaktywności. Dane konta i gry pozostają do czasu usunięcia konta. Usunięcie rozstrzyga aktywny mecz i usuwa konto, profil, ustawienia, wpisy kolejki i rankingu, historię meczów i ruchów, runy i postępy. Techniczne potwierdzenia zapobiegające powtórzeniu poleceń gry kwalifikują się do cogodzinnego usuwania, gdy zarówno od utworzenia potwierdzenia, jak i od zakończenia powiązanego meczu upłynie więcej niż {{commandReceiptRetentionDays}} dni.'), p('Po usunięciu konta połączonego z Apple poświadczenie nadal potrzebne do automatycznego cofnięcia połączenia pozostaje zaszyfrowane przez okres ponownych prób do {{appleRevocationRetryDays}} dni, po czym usuwa je zaplanowany proces. Zaplanowany proces sprawdza oczekujące ponowienia co {{appleRevocationScheduleMinutes}} minut; poszczególne próby mogą nastąpić później. Jeżeli cofnięcie połączenia nie powiedzie się automatycznie, skorzystaj z ręcznych instrukcji w części Usuń konto.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('Lokalne ustawienia offline, statystyki i pliki gry w pamięci podręcznej pozostają do czasu usunięcia danych aplikacji lub strony w przeglądarce. Samo usunięcie konta na serwerze nie usuwa tych danych offline.')] },
        { id: 'support', heading: 'Pomoc i wnioski dotyczące prywatności', blocks: [p('Gdy się z nami kontaktujesz, przetwarzamy adres nadawcy, wiadomość i informacje, które zdecydujesz się dołączyć, np. wersję aplikacji, pseudonim lub zrzut ekranu. Używamy tylko danych niezbędnych do odpowiedzi na pytanie lub zbadania zgłoszonego problemu (art. 6 ust. 1 lit. f RODO); podstawę prawną ustawowych wniosków dotyczących prywatności opisano powyżej. Nie wysyłaj haseł ani linków uwierzytelniających.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'Twoje prawa', blocks: [p('Na warunkach określonych w przepisach możesz żądać dostępu do swoich danych, ich sprostowania, usunięcia lub ograniczenia przetwarzania. Prawo do przenoszenia danych dotyczy przetwarzania zautomatyzowanego opartego na zgodzie lub umowie. Jeśli podstawą przetwarzania jest zgoda, możesz ją wycofać na przyszłość bez wpływu na zgodność z prawem wcześniejszego przetwarzania.'), p('Napisz na {{publicEmail}}. Zwykle odpowiadamy bez zbędnej zwłoki, w ciągu miesiąca. Jeżeli konieczne jest dozwolone prawem przedłużenie terminu, wyjaśnimy przyczynę w tym pierwszym miesiącu. {{deletionVerification}}'), p('Możesz złożyć skargę do organu ochrony danych, m.in. w miejscu zamieszkania, pracy lub domniemanego naruszenia. Organem właściwym dla tego usługodawcy jest {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Informacje i kontakt w sprawie skarg: https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'Prawo do sprzeciwu', blocks: [p('Jeżeli przetwarzanie opiera się na art. 6 ust. 1 lit. f RODO, możesz w dowolnym momencie wnieść sprzeciw z przyczyn związanych ze swoją szczególną sytuacją. Napisz na {{publicEmail}}. Zaprzestaniemy tego przetwarzania, chyba że wykażemy ważne prawnie uzasadnione podstawy nadrzędne wobec Twoich interesów, praw i wolności lub przetwarzanie jest potrzebne do ustalenia, dochodzenia lub obrony roszczeń.')] },
        { id: 'children', heading: 'Dzieci i rodzice', blocks: [p('Knucklebones Neon to gra dla ogólnej grupy odbiorców. Nie pyta o wiek ani datę urodzenia. Gra lokalna nie wymaga konta rankingowego. Gra online zapisuje opisane tutaj dane konta i gry, także w przypadku młodszych graczy.'), p('Jeśli jesteś młodą osobą: używaj wymyślonego pseudonimu, zachowaj hasło w tajemnicy i poproś zaufaną osobę dorosłą o pomoc w sprawach konta lub prywatności. Inne osoby mogą widzieć Twój pseudonim i wyniki gry. W tej grze nie ma czatu między graczami, reklam ani płatności.'), p('Rodzice i opiekunowie mogą pisać na {{publicEmail}} w sprawie konta dziecka, dostępu do danych lub ich usunięcia. Prosimy wyłącznie o informacje potrzebne do ustalenia konta i uprawnienia do działania. Gdy obowiązujące prawo wymaga zgody rodzica, korzystanie z konta Apple ani dalsza gra nie zastępują takiej zgody.')] },
        { id: 'automated-decisions', heading: 'Dobieranie graczy i automatyczne obliczenia', blocks: [p('Gra automatycznie oblicza wyniki, pozycje, odblokowania i dobiera przeciwników na podstawie danych gry; może też dobrać przeciwnika sterowanego komputerowo. Te funkcje gry nie podejmują wobec Ciebie decyzji wywołujących skutki prawne lub podobnie istotnie na Ciebie wpływających w rozumieniu art. 22 RODO.')] },
        { id: 'changes', heading: 'Data i zmiany', blocks: [p('Ostatnia aktualizacja: {{noticeDate}}. Aktualizujemy tę informację, gdy zmienia się gra lub przetwarzanie danych. Bieżąca wersja jest dostępna w aplikacji i na publicznej stronie prywatności. Istotne zmiany wyjaśniamy przed rozpoczęciem zmienionego przetwarzania.')] },
      ],
    },
    support: {
      title: 'Pomoc i kontakt',
      shortTitle: 'Pomoc',
      description: 'Pomoc dotycząca Knucklebones Neon, prywatności i kont.',
      intro: 'Skontaktuj się z nami w sprawie problemów z grą, pomocy z kontem lub prywatności.',
      sections: [
        { id: 'contact', heading: 'Kontakt', blocks: [p('E-mail: {{publicEmail}}')] },
        { id: 'help', heading: 'W czym możemy pomóc', blocks: [list('Problemy techniczne i dostępność', 'Konta rankingowe i pseudonimy', 'Prawa do ochrony danych i usuwanie kont', 'Zgłoszenia bezpieczeństwa lub nadużyć', 'Pytania rodziców o konto dziecka')] },
        { id: 'details', heading: 'Co podać', blocks: [p('Opisz zdarzenie i podaj wersję aplikacji lub przeglądarki. Dołącz pseudonim lub potwierdzony e-mail konta tylko wtedy, gdy są potrzebne do znalezienia konta. Usuń prywatne dane innych osób ze zrzutów ekranu.')] },
        { id: 'credentials', heading: 'Chroń dane logowania', blocks: [p('Nigdy nie wysyłaj hasła, linku logowania lub odzyskiwania, tokena dostępu, kodu autoryzacji Apple ani prywatnych danych innych osób. Nie prosimy o takie poświadczenia e-mailem.')] },
        { id: 'handling', heading: 'Jak obsługujemy wnioski', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Na ustawowe wnioski dotyczące prywatności zwykle odpowiadamy w ciągu miesiąca; w tym terminie wyjaśniamy też ewentualne dozwolone przedłużenie i jego przyczynę.')] },
      ],
    },
    'delete-account': {
      title: 'Usuń swoje konto',
      shortTitle: 'Usuń konto',
      description: 'Jak usunąć konto rankingowe Knucklebones Neon w aplikacji lub poza nią.',
      intro: 'Usunięcie konta rankingowego jest trwałe. Możesz bez niego kontynuować grę lokalną.',
      sections: [
        { id: 'in-app', heading: 'Usuń konto w aplikacji', blocks: [list('Otwórz profil na ekranie głównym.', 'Otwórz ustawienia konta.', 'Wybierz Usuń konto i przeczytaj wyjaśnienie.', 'Potwierdź trwałe usunięcie.')] },
        { id: 'server-data', heading: 'Co jest usuwane', blocks: [p('Gra rozstrzyga aktywny mecz i usuwa konto na serwerze, profil, ustawienia, wpisy kolejki i rankingu, historię meczów i ruchów, runy oraz postępy. Tej tożsamości rankingowej i jej wyników nie można przywrócić w aplikacji.')] },
        { id: 'local-data', heading: 'Dane offline na urządzeniu', blocks: [p('Usunięcie konta wylogowuje Cię oraz usuwa lokalną sesję konta i profil z pamięci podręcznej. Ustawienia offline, statystyki i zapisane pliki gry pozostają. Aby usunąć również te dane, wyczyść dane tej strony w przeglądarce. Na Androidzie wyczyść pamięć lub dane aplikacji w ustawieniach urządzenia. Na iOS wybierz Usuń aplikację; opcja Odinstaluj aplikację zachowuje jej dokumenty i dane. Samo wyczyszczenie danych urządzenia nie usuwa konta na serwerze.')] },
        { id: 'external', heading: 'Wniosek o usunięcie bez aplikacji', blocks: [p('Napisz na {{publicEmail}}, że chcesz usunąć konto rankingowe Knucklebones Neon. Użyj potwierdzonego e-maila konta, jeśli nadal masz do niego dostęp. Podaj pseudonim tylko wtedy, gdy jest potrzebny do odnalezienia konta. Nie wysyłaj danych logowania. Rodzic lub opiekun również może skontaktować się z nami w sprawie konta dziecka.')] },
        { id: 'verification', heading: 'Weryfikacja właściciela i pozostałe kopie', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Konto połączone z Apple', blocks: [p('Usunięcie podejmuje również próbę cofnięcia połączenia logowania przez Apple. Przejściowe błędy są ponawiane przez okres do {{appleRevocationRetryDays}} dni. Jeśli automatyczne cofnięcie się nie powiedzie, postępuj zgodnie z instrukcjami w aplikacji lub usuń połączenie aplikacji w ustawieniach konta Apple. Nie usuwa to Twojego konta Apple. Odrębne konto Game Center również nie jest usuwane.')] },
      ],
    },
  },
};
