import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const PT_LEGAL: LegalLocaleContent = {
  siteTitle: 'Informações legais do Knucklebones Neon',
  languageLabel: 'Idioma',
  pageNavigationLabel: 'Informações legais',
  languageNavigationLabel: 'Idiomas disponíveis',
  homeLabel: 'Voltar ao jogo',
  backLabel: 'Voltar',
  pendingFact: 'Aguardando verificação antes da publicação',
  pages: {
    imprint: {
      title: 'Informações do responsável',
      shortTitle: 'Aviso legal',
      description: 'Informações do responsável e de contato do Knucklebones Neon.',
      intro: 'A pessoa física abaixo é responsável pelo Knucklebones Neon.',
      sections: [
        { id: 'provider', heading: 'Responsável conforme o § 18(1) MStV', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'Contato', blocks: [p('E-mail: {{publicEmail}}')] },
        { id: 'project', heading: 'Sobre este projeto', blocks: [p('Knucklebones Neon é um jogo gratuito, desenvolvido como hobby e sem fins comerciais. Não há publicidade, compras, assinaturas nem doações.')] },
      ],
    },
    privacy: {
      title: 'Aviso de privacidade',
      shortTitle: 'Privacidade',
      description: 'Como o Knucklebones Neon trata dados do dispositivo, da conta e do jogo online.',
      intro: 'Você pode jogar localmente sem uma conta de partidas ranqueadas. Para jogar online, é preciso uma conta para salvar seu progresso e encontrar adversários. Este aviso explica quais dados são usados, quem os recebe e como você pode excluí-los.',
      sections: [
        { id: 'controller', heading: 'Quem é responsável', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Para dúvidas ou solicitações de privacidade, escreva para {{publicEmail}}.')] },
        { id: 'scope', heading: 'Onde este aviso se aplica', blocks: [p('Este aviso abrange o site, o aplicativo web instalado, o jogo independente, o widget incorporado e os aplicativos nativos do Knucklebones Neon. A Cloudflare distribui o site e seus arquivos. Os aplicativos nativos carregam os arquivos do jogo a partir do pacote instalado, mas as funções online continuam se conectando aos respectivos prestadores de serviço. Se você jogar em um widget em outro site, esse site também poderá tratar dados conforme seu próprio aviso de privacidade.'), p('Não integramos publicidade, análise comportamental nem SDKs de rastreamento. O jogo não solicita sua localização, contatos, câmera ou fotos e não oferece chat entre jogadores nem envio de imagens. Os dados operacionais e de segurança tratados pelos nossos provedores de infraestrutura são descritos abaixo.')] },
        { id: 'device-storage', heading: 'Dados armazenados no seu dispositivo', blocks: [p('O navegador ou aplicativo armazena o idioma escolhido, as configurações de acessibilidade e do jogo, além das pontuações e estatísticas locais. Para contas online, também armazena credenciais de sessão e cópias locais do perfil, das informações de contas vinculadas, das partidas recentes, das runas e do progresso. Essas cópias da conta também são mantidas no servidor; não são dados exclusivamente locais.'), p('O aplicativo web mantém arquivos do jogo em cache para funcionar offline. Também armazena brevemente um sinalizador de recuperação quando um arquivo do programa não é carregado. Esses usos incluem armazenamento local do navegador, armazenamento de sessão e cache de arquivos do aplicativo; não são cookies publicitários.'), p('O armazenamento e o acesso necessários para fornecer uma função que você solicita se baseiam no § 25(2)(2) TDDDG. O tratamento de dados pessoais para essas funções segue as finalidades e bases legais abaixo. Para remover os dados locais, siga as instruções específicas para o seu dispositivo em Excluir conta. Apagar uma sessão de convidado sem opção de recuperação pode impedir que você acesse essa conta novamente.')] },
        { id: 'accounts', heading: 'Contas de convidado, e-mail e progresso', blocks: [p('Quando você solicita uma partida ranqueada, o jogo usa ou restaura sua conta existente. Quando possível no iOS, usa sua identidade vinculada do Game Center. Caso contrário, cria uma conta de convidado sem pedir nome ou e-mail. “Convidado” não significa que os dados sejam anônimos: a conta tem um identificador persistente.'), p('Os dados da conta incluem o identificador, um apelido gerado ou escolhido, um avatar predefinido, configurações, pontuação atual e máxima, resultados ranqueados, vitórias, derrotas, sequências, data e hora de criação do perfil, partidas e jogadas. Runas, conteúdo desbloqueado, conquistas, desafios semanais e outros dados de progresso também são salvos.'), p('Cadastro, login e recuperação com e-mail e senha são opcionais. O Supabase Auth trata o endereço de e-mail e as credenciais de senha para essas funções. {{smtpProvider}} entrega as mensagens de confirmação de conta e recuperação. Você pode jogar como convidado sem informar um e-mail, mas as opções de recuperação serão limitadas. Os dados necessários da conta online e das jogadas não podem ser omitidos durante o uso de partidas ranqueadas.')] },
        { id: 'apple', heading: 'Iniciar Sessão com a Apple e Game Center', blocks: [p('No iOS, a autenticação do Game Center é inicializada quando o aplicativo é aberto. Por isso, a Apple pode tratar dados do Game Center antes de você iniciar uma partida ranqueada. O jogo usa o estado de autenticação da Apple e um identificador de jogador específico da equipe de desenvolvimento para restaurar ou vincular sua conta de partidas ranqueadas e protegê-la quando a conta do Game Center no dispositivo muda. Dados de verificação assinados passam por um gateway da Cloudflare até o Supabase. Essa integração não nos fornece seus amigos, foto de perfil ou nome de perfil público do Game Center.'), p('Se você escolher Iniciar Sessão com a Apple, a Apple fornece um identificador de conta, dados de autenticação assinados e, quando disponibilizado, seu endereço de e-mail real ou o endereço de retransmissão privada da Apple. Um código de autorização é trocado para permitir a revogação posterior. A credencial de atualização resultante é criptografada no Supabase Vault e usada apenas para revogar a conexão com a Apple quando você exclui a conta.'), p('A Apple opera seus serviços de conta e Game Center conforme seus próprios termos e informações de privacidade: https://www.apple.com/legal/privacy/ e https://www.apple.com/legal/privacy/data/en/game-center/. Você controla o Game Center nas configurações do seu dispositivo Apple.')] },
        { id: 'purposes', heading: 'Por que tratamos dados e quais são as bases legais', blocks: [p('Tratamos os dados necessários para o jogo gratuito solicitado, o acesso e a recuperação da conta, o progresso salvo, o pareamento, a validação de partidas e os resultados ranqueados com base em interesses legítimos (artigo 6(1)(f) do GDPR). Nossos interesses são fornecer as funções que você escolhe, preservar seu progresso e manter um jogo justo e confiável. As informações públicas do perfil se limitam aos dados do jogo descritos abaixo; não precisamos do seu nome real.'), p('Também tratamos dados necessários de solicitações e segurança, como endereços IP, horários das solicitações, informações do navegador ou aplicativo, status das respostas e informações de erros, para fornecer o serviço, prevenir uso indevido, limitar solicitações excessivas e investigar falhas (artigo 6(1)(f) do GDPR). Para solicitações relativas a direitos de privacidade, o tratamento necessário ao cumprimento das nossas obrigações se baseia no artigo 6(1)(c) em conjunto com os artigos 12 a 22 do GDPR.')] },
        { id: 'recipients', heading: 'Prestadores de serviço e tratamento internacional', blocks: [p('O Supabase fornece autenticação hospedada, banco de dados, conexões de jogo em tempo real e funções de servidor. Região do banco de dados: {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Os e-mails de conta são enviados por {{smtpProvider}}. A Apple também trata dados para os serviços Apple descritos acima. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'O que outras pessoas podem ver', blocks: [p('Ao jogar partidas ranqueadas, você participa de uma classificação pública. Seu apelido, avatar predefinido, pontuação atual e máxima, posição ou status no topo da classificação, vitórias, derrotas, partidas jogadas, melhor sequência, data de entrada e resultados ranqueados podem aparecer no ranking e nos cartões de jogador. Esses resumos públicos de perfil também podem ser consultados sem uma conta conectada. Escolha um apelido que não revele seu nome real ou dados de contato.'), p('Seu e-mail, suas credenciais de senha e seus dados de autenticação da Apple não são públicos. O histórico detalhado da conta fica visível apenas para o titular; os dois participantes podem acessar o histórico da partida e das jogadas que compartilharam.')] },
        { id: 'retention', heading: 'Por quanto tempo os dados são armazenados', blocks: [p('Atualmente, contas de convidado e contas recuperáveis não expiram automaticamente por inatividade. Os dados da conta e do jogo permanecem até a exclusão da conta. A exclusão resolve qualquer partida ativa e remove a conta, o perfil, as configurações, as entradas na fila e no ranking, o histórico de partidas e jogadas, as runas e o progresso. Os registros técnicos usados para evitar comandos de jogo duplicados passam a poder ser removidos pela limpeza executada a cada hora quando tanto a criação do registro quanto o encerramento da partida correspondente ocorreram há mais de {{commandReceiptRetentionDays}} dias.'), p('Após a exclusão de uma conta vinculada à Apple, qualquer credencial ainda necessária para a revogação automática é mantida criptografada por um período de novas tentativas de até {{appleRevocationRetryDays}} dias e, depois, é removida pelo processamento agendado. O processamento agendado é executado a cada {{appleRevocationScheduleMinutes}} minutos; as novas tentativas individuais podem ocorrer mais tarde. Se a revogação não puder ser concluída automaticamente, use as instruções manuais descritas em Excluir conta.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('As configurações offline locais, estatísticas e arquivos do jogo em cache permanecem até você limpar os dados do aplicativo ou do site no navegador. Excluir apenas a conta do servidor não remove esses itens offline.')] },
        { id: 'support', heading: 'Suporte e solicitações de privacidade', blocks: [p('Se você entrar em contato conosco, trataremos seu endereço de remetente, sua mensagem e as informações que decidir incluir, como a versão do aplicativo, seu apelido ou uma captura de tela. Usamos apenas o necessário para responder à sua dúvida ou investigar o problema relatado (artigo 6(1)(f) do GDPR); a base legal para solicitações de direitos de privacidade previstas em lei é descrita acima. Não envie senhas nem links de autenticação.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'Seus direitos', blocks: [p('Observadas as condições legais aplicáveis, você pode solicitar acesso aos seus dados pessoais, correção, exclusão ou restrição do tratamento. A portabilidade dos dados se aplica quando o tratamento é automatizado e se baseia em consentimento ou contrato. Se o tratamento se basear em consentimento, você poderá retirá-lo para o futuro sem afetar a legalidade do tratamento anterior.'), p('Entre em contato pelo e-mail {{publicEmail}}. Normalmente respondemos sem demora injustificada e dentro de um mês. Se for necessária uma prorrogação permitida por lei, explicaremos o motivo dentro desse primeiro mês. {{deletionVerification}}'), p('Você pode apresentar uma reclamação a uma autoridade de proteção de dados, inclusive à autoridade do lugar onde mora, trabalha ou acredita que ocorreu uma infração. A autoridade responsável por este prestador é {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Informações e contato para reclamações: https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'Seu direito de oposição', blocks: [p('Quando o tratamento se baseia no artigo 6(1)(f) do GDPR, você pode se opor a qualquer momento por motivos relacionados à sua situação particular. Escreva para {{publicEmail}}. Interromperemos esse tratamento, a menos que possamos demonstrar motivos legítimos imperiosos que prevaleçam sobre seus interesses, direitos e liberdades, ou que o tratamento seja necessário para estabelecer, exercer ou defender direitos em processos judiciais.')] },
        { id: 'children', heading: 'Crianças e responsáveis', blocks: [p('Knucklebones Neon é um jogo para o público em geral. Não há pergunta sobre idade nem solicitação de data de nascimento. Para jogar localmente, não é preciso uma conta de partidas ranqueadas. O jogo online armazena as informações da conta e do jogo descritas aqui, inclusive as de jogadores mais jovens.'), p('Se você é jovem: use um apelido inventado, mantenha sua senha em segredo e peça ajuda a um adulto de confiança se tiver dúvidas sobre sua conta ou privacidade. Outras pessoas podem ver seu apelido e seus resultados. Este jogo não tem chat entre jogadores, publicidade nem pagamentos.'), p('Pais e responsáveis podem entrar em contato pelo e-mail {{publicEmail}} sobre a conta de uma criança, acesso a dados ou exclusão. Solicitamos apenas as informações necessárias para identificar a conta e comprovar a autorização para agir em nome da criança. Quando a lei aplicável exige autorização dos pais ou responsáveis, usar uma conta Apple ou continuar jogando não substitui essa autorização.')] },
        { id: 'automated-decisions', heading: 'Pareamento e cálculos automáticos', blocks: [p('O jogo calcula automaticamente pontuações, posições, desbloqueios e adversários adequados a partir dos dados do jogo e pode colocar você contra um adversário controlado pelo computador. Essas funções do jogo não tomam decisões que produzam efeitos jurídicos ou efeitos igualmente significativos sobre você nos termos do artigo 22 do GDPR.')] },
        { id: 'changes', heading: 'Data e alterações', blocks: [p('Última atualização: {{noticeDate}}. Atualizamos este aviso quando o jogo ou o tratamento de dados muda. A versão atual está disponível no aplicativo e na página pública de privacidade. Alterações relevantes são explicadas antes do início do tratamento modificado.')] },
      ],
    },
    support: {
      title: 'Suporte e contato',
      shortTitle: 'Suporte',
      description: 'Ajuda com Knucklebones Neon, privacidade e contas.',
      intro: 'Entre em contato para problemas com o jogo, ajuda com a conta ou solicitações de privacidade.',
      sections: [
        { id: 'contact', heading: 'Contato', blocks: [p('E-mail: {{publicEmail}}')] },
        { id: 'help', heading: 'Como podemos ajudar', blocks: [list('Problemas técnicos e de acessibilidade', 'Contas de partidas ranqueadas e apelidos', 'Direitos de privacidade e exclusão da conta', 'Relatos de problemas de segurança ou abuso', 'Dúvidas de pais e responsáveis sobre a conta de uma criança')] },
        { id: 'details', heading: 'O que informar', blocks: [p('Descreva o que aconteceu e informe a versão do aplicativo ou navegador. Inclua seu apelido ou e-mail confirmado da conta apenas se necessário para localizar a conta. Remova informações privadas de outras pessoas das capturas de tela.')] },
        { id: 'credentials', heading: 'Mantenha suas credenciais em segredo', blocks: [p('Nunca envie sua senha, link de login ou recuperação, token de acesso, código de autorização da Apple ou dados privados de outra pessoa. Não pedimos essas credenciais por e-mail.')] },
        { id: 'handling', heading: 'Como as solicitações são tratadas', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Solicitações de direitos de privacidade previstos em lei normalmente são respondidas dentro de um mês; qualquer prorrogação permitida e seu motivo são explicados dentro desse prazo.')] },
      ],
    },
    'delete-account': {
      title: 'Excluir sua conta',
      shortTitle: 'Excluir conta',
      description: 'Como excluir uma conta de partidas ranqueadas do Knucklebones Neon dentro ou fora do aplicativo.',
      intro: 'A exclusão da sua conta de partidas ranqueadas é permanente. Você pode continuar jogando localmente sem ela.',
      sections: [
        { id: 'in-app', heading: 'Excluir no aplicativo', blocks: [list('Abra seu perfil na tela inicial.', 'Abra os controles da conta.', 'Escolha Excluir conta e leia a explicação.', 'Confirme a exclusão permanente.')] },
        { id: 'server-data', heading: 'O que é excluído', blocks: [p('O jogo resolve qualquer partida ativa e exclui sua conta hospedada, perfil, configurações, entradas na fila e no ranking, histórico de partidas e jogadas, runas e progresso. Essa identidade de partidas ranqueadas e seus resultados não podem ser restaurados pelo aplicativo.')] },
        { id: 'local-data', heading: 'Dados offline no seu dispositivo', blocks: [p('A exclusão da conta encerra sua sessão e limpa a sessão local da conta e o perfil em cache. Suas configurações offline, estatísticas e arquivos do jogo em cache permanecem. Para removê-los também, limpe os dados deste site no navegador. No Android, limpe o armazenamento ou os dados do aplicativo nas configurações do dispositivo. No iOS, apague o aplicativo; a opção de desinstalar sem apagar os dados mantém seus documentos e dados. Limpar apenas os dados do dispositivo não exclui a conta do servidor.')] },
        { id: 'external', heading: 'Solicitar exclusão sem o aplicativo', blocks: [p('Escreva para {{publicEmail}} e informe que deseja excluir sua conta de partidas ranqueadas do Knucklebones Neon. Use o e-mail confirmado da conta se ainda tiver acesso a ele. Inclua um apelido apenas se necessário para localizar a conta. Não envie credenciais de login. Um pai, uma mãe ou um responsável também pode entrar em contato sobre a conta de uma criança.')] },
        { id: 'verification', heading: 'Verificação de titularidade e cópias restantes', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Conta vinculada à Apple', blocks: [p('A exclusão também tenta revogar a conexão do Iniciar Sessão com a Apple. Em caso de falhas temporárias, novas tentativas são feitas por até {{appleRevocationRetryDays}} dias. Se a revogação automática não puder ser concluída, siga as instruções no aplicativo ou remova a conexão do aplicativo nas configurações da sua conta Apple. Isso não exclui sua conta Apple. Sua conta separada do Game Center também não é excluída.')] },
      ],
    },
  },
};
