import type { LegalContentBlock, LegalLocaleContent } from '../types.ts';

const p = (text: string): LegalContentBlock => ({ kind: 'paragraph', text });
const list = (...items: string[]): LegalContentBlock => ({ kind: 'list', items });

export const TR_LEGAL: LegalLocaleContent = {
  siteTitle: 'Knucklebones Neon yasal bilgileri',
  languageLabel: 'Dil',
  pageNavigationLabel: 'Yasal bilgiler',
  languageNavigationLabel: 'Kullanılabilir diller',
  homeLabel: 'Oyuna dön',
  backLabel: 'Geri',
  pendingFact: 'Yayımlanmadan önce doğrulanacak',
  pages: {
    imprint: {
      title: 'Sağlayıcı bilgileri',
      shortTitle: 'Yasal bilgiler',
      description: 'Knucklebones Neon sağlayıcı ve iletişim bilgileri.',
      intro: 'Knucklebones Neon hizmetini sunan kişi aşağıdaki gerçek kişidir.',
      sections: [
        { id: 'provider', heading: 'MStV § 18(1) uyarınca sağlayıcı', blocks: [p('{{controllerName}}\n{{controllerStreet}}\n{{controllerPostalCity}}\n{{controllerCountry}}')] },
        { id: 'contact', heading: 'İletişim', blocks: [p('E-posta: {{publicEmail}}')] },
        { id: 'project', heading: 'Proje hakkında', blocks: [p('Knucklebones Neon ücretsiz, ticari olmayan bir hobi oyunudur. Reklam, satın alma, abonelik veya bağış içermez.')] },
      ],
    },
    privacy: {
      title: 'Gizlilik bildirimi',
      shortTitle: 'Gizlilik',
      description: 'Knucklebones Neon cihaz, hesap ve çevrimiçi oyun verilerini nasıl işler.',
      intro: 'Dereceli hesap olmadan yerel olarak oynayabilirsin. Çevrimiçi oyun, ilerlemeni kaydetmek ve seni rakiplerle eşleştirmek için bir hesap gerektirir. Bu bildirim hangi verilerin kullanıldığını, kimlere aktarıldığını ve bunları nasıl silebileceğini açıklar.',
      sections: [
        { id: 'controller', heading: 'Verilerden kim sorumlu', blocks: [p('{{controllerName}}, {{controllerStreet}}, {{controllerPostalCity}}, {{controllerCountry}}. Gizlilik soruların veya taleplerin için {{publicEmail}} adresine yaz.')] },
        { id: 'scope', heading: 'Bu bildirimin kapsamı', blocks: [p('Bu bildirim web sitesini, yüklü web uygulamasını, bağımsız oyunu, başka sitelere gömülen widget bileşenini ve yerel Knucklebones Neon uygulamalarını kapsar. Web sitesini ve dosyalarını Cloudflare sunar. Yerel uygulamalar oyun dosyalarını yüklü paketten açar; çevrimiçi işlevler ise hizmet sağlayıcılarıyla iletişim kurmaya devam eder. Başka bir sitedeki widget üzerinden oynarsan o site de kendi gizlilik bildirimine göre veri işleyebilir.'), p('Reklam, davranış analizi veya takip SDK’ları kullanmıyoruz. Oyun konumuna, kişilerine, kamerana veya fotoğraflarına erişim istemez; oyuncu sohbeti veya resim yükleme işlevi de yoktur. Altyapı sağlayıcılarımızın işlediği işletim ve güvenlik verileri aşağıda açıklanmıştır.')] },
        { id: 'device-storage', heading: 'Cihazında saklanan veriler', blocks: [p('Tarayıcı veya uygulama seçtiğin dili, erişilebilirlik ve oyun ayarlarını, yerel skorları ve istatistikleri saklar. Çevrimiçi hesaplar için oturum kimlik bilgilerini ve profilinin, bağlı hesap bilgilerinin, son maçlarının, rünlerinin ve ilerlemenin yerel kopyalarını da saklar. Bu hesap verileri sunucuda da tutulur; yalnızca cihazında bulunan veriler değildir.'), p('Web uygulaması çevrimdışı çalışabilmek için oyun dosyalarını önbelleğe alır. Bir program dosyası yüklenemediğinde kısa süreli bir kurtarma işareti de saklar. Bunlar için tarayıcının yerel depolaması, oturum depolaması ve uygulama dosyası önbelleği kullanılır; bunlar reklam çerezleri değildir.'), p('İstediğin bir işlevi sunmak için gerekli saklama ve erişim işlemlerinin dayanağı TDDDG § 25(2)(2) hükmüdür. Bu işlevler için kişisel verilerin işlenmesi aşağıda açıklanan amaçlara ve hukuki dayanaklara tabidir. Yerel verileri kaldırmak için Hesabı sil bölümündeki cihazına özel adımları izle. Kurtarılamayan bir misafir oturumunu silmek, o hesaba tekrar erişmeni engelleyebilir.')] },
        { id: 'accounts', heading: 'Misafir hesapları, e-posta ve ilerleme', blocks: [p('Dereceli oynamayı seçtiğinde oyun mevcut hesabını kullanır veya geri yükler. iOS’ta mümkün olduğunda bağlı Game Center kimliğini kullanır. Aksi halde adını veya e-posta adresini sormadan bir misafir hesabı oluşturur. “Misafir” verilerin anonim olduğu anlamına gelmez: hesabın kalıcı bir tanımlayıcısı vardır.'), p('Hesap verileri; tanımlayıcıyı, oluşturulan veya seçilen takma adı, hazır avatarlardan seçimini, ayarlarını, mevcut ve en yüksek puanlarını, dereceli sonuçlarını, galibiyetlerini, mağlubiyetlerini, serilerini, profil oluşturma zamanını, maçlarını ve hamlelerini içerir. Rünler, açılan içerikler, başarımlar, haftalık görevler ve diğer ilerlemeler de kaydedilir.'), p('E-posta ve parolayla kayıt, giriş ve hesap kurtarma isteğe bağlıdır. Supabase Auth bu işlevler için e-posta adresini ve parola kimlik bilgilerini işler. {{smtpProvider}} hesap doğrulama ve kurtarma iletilerini gönderir. E-posta vermeden misafir olarak oynayabilirsin, ancak kurtarma seçenekleri o zaman sınırlıdır. Dereceli oynarken gerekli çevrimiçi hesap ve hamle verilerinin işlenmesi zorunludur.')] },
        { id: 'apple', heading: 'Apple ile giriş ve Game Center', blocks: [p('iOS’ta Game Center kimlik doğrulaması uygulama açıldığında başlatılır. Bu nedenle Apple, dereceli bir maça başlamadan önce de Game Center verilerini işleyebilir. Oyun, dereceli hesabını geri yüklemek veya bağlamak ve cihazdaki Game Center hesabı değiştiğinde hesabını korumak için Apple kimlik doğrulama durumunu ve geliştirici ekibi kapsamındaki oyuncu tanımlayıcısını kullanır. İmzalı doğrulama verileri bir Cloudflare ağ geçidinden Supabase’e ulaşır. Bu entegrasyonla Game Center arkadaşlarını, profil fotoğrafını veya herkese açık profil adını almayız.'), p('Apple ile giriş yapmayı seçersen Apple hesap tanımlayıcısını, imzalı kimlik doğrulama verilerini ve sağlandığında gerçek e-posta adresini veya Apple’ın özel yönlendirme adresini iletir. Bağlantının daha sonra iptal edilebilmesi için bir yetkilendirme kodu takas edilir. Elde edilen yenileme kimlik bilgisi Supabase Vault içinde şifrelenir ve yalnızca hesabını sildiğinde Apple bağlantısını iptal etmek için kullanılır.'), p('Apple, hesap ve Game Center hizmetlerini kendi koşulları ve gizlilik bilgileri kapsamında sunar: https://www.apple.com/legal/privacy/ ve https://www.apple.com/legal/privacy/data/en/game-center/. Game Center’ı Apple cihazının ayarlarından yönetebilirsin.')] },
        { id: 'purposes', heading: 'İşleme amaçları ve hukuki dayanaklar', blocks: [p('İstediğin ücretsiz oyun, hesaba erişim ve hesap kurtarma, ilerlemeyi kaydetme, rakip eşleştirme, oyun doğrulama ve dereceli sonuçlar için gerekli verileri meşru menfaatlere dayanarak işleriz (GDPR Madde 6(1)(f)). Menfaatlerimiz, seçtiğin işlevleri sunmak, oyun ilerlemeni korumak ve adil, güvenilir bir oyun işletmektir. Herkese açık profil, aşağıda açıklanan oyun bilgileriyle sınırlıdır; gerçek adına ihtiyacımız yoktur.'), p('Hizmeti sunmak, kötüye kullanımı önlemek, aşırı istekleri sınırlamak ve hataları araştırmak için IP adresleri, istek zamanları, tarayıcı veya uygulama bilgileri, yanıt durumu ve hata bilgileri gibi gerekli istek ve güvenlik verilerini de işleriz (GDPR Madde 6(1)(f)). Gizlilik haklarına ilişkin taleplerde yükümlülüklerimizi yerine getirmek için gerekli işlemenin dayanağı, GDPR Madde 12–22 ile birlikte Madde 6(1)(c) hükmüdür.')] },
        { id: 'recipients', heading: 'Sağlayıcılar ve uluslararası işleme', blocks: [p('Supabase barındırılan kimlik doğrulama, veritabanı, gerçek zamanlı oyun bağlantıları ve sunucu işlevleri sunar. Veritabanı bölgesi: {{supabaseDatabaseRegion}}. {{supabaseFunctionsRegion}}'), p('{{cloudflareProcessingScope}}'), p('Hesap e-postaları {{smtpProvider}} aracılığıyla gönderilir. Apple ayrıca yukarıda açıklanan Apple hizmetleri için veri işler. {{supportProcessing}}'), p('{{transferSafeguards}}')] },
        { id: 'public-profile', heading: 'Başkalarının görebilecekleri', blocks: [p('Dereceli oyun oynadığında herkese açık bir sıralamaya katılırsın. Takma adın, hazır avatarın, mevcut ve en yüksek puanların, sıran veya zirve durumun, galibiyetlerin, mağlubiyetlerin, oynadığın maç sayısı, en iyi serin, üyelik başlangıç zamanın ve dereceli sonuçların sıralamada ve oyuncu kartlarında gösterilebilir. Bu herkese açık profil özetlerine giriş yapılmış bir hesap olmadan da erişilebilir. Gerçek adını veya iletişim bilgilerini açıklamayan bir takma ad seç.'), p('E-posta adresin, parola kimlik bilgilerin ve Apple kimlik doğrulama verilerin herkese açık değildir. Ayrıntılı hesap geçmişini yalnızca hesap sahibi görebilir; maçın iki katılımcısı ortak maç ve hamle geçmişlerine erişebilir.')] },
        { id: 'retention', heading: 'Verilerin saklanma süresi', blocks: [p('Misafir hesapları ve kurtarılabilir hesaplar şu anda hareketsizlik nedeniyle otomatik olarak sona ermez. Hesap ve oyun verileri hesap silinene kadar kalır. Silme işlemi etkin bir maçı sonuçlandırır; hesabı, profili, ayarları, kuyruk ve sıralama kayıtlarını, maç ve hamle geçmişini, rünleri ve ilerlemeyi kaldırır. Oyun komutlarının yinelenmesini önleyen teknik işlem kayıtları, hem kaydın oluşturulmasının hem de ilgili maçın sona ermesinin üzerinden {{commandReceiptRetentionDays}} günden fazla zaman geçtiğinde saatlik temizlik işleminde silinmeye uygun hâle gelir.'), p('Apple’a bağlı bir hesap silindikten sonra otomatik iptal için hâlâ gereken kimlik bilgisi, en fazla {{appleRevocationRetryDays}} günlük yeniden deneme süresi boyunca şifreli tutulur ve ardından zamanlanmış işlemle kaldırılır. Zamanlanmış işlem, bekleyen yeniden denemeleri {{appleRevocationScheduleMinutes}} dakikada bir kontrol eder; tek tek denemeler daha sonra gerçekleşebilir. İptal otomatik olarak tamamlanamazsa Hesabı sil bölümündeki elle kaldırma talimatlarını kullan.'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{smtpRetention}}'), p('Yerel çevrimdışı ayarlar, istatistikler ve önbellekteki oyun dosyaları, uygulama veya tarayıcı site verilerini silene kadar kalır. Yalnızca sunucu hesabını silmek bu çevrimdışı öğeleri kaldırmaz.')] },
        { id: 'support', heading: 'Destek ve gizlilik talepleri', blocks: [p('Bize ulaşırsan gönderen adresini, iletini ve uygulama sürümü, takma ad veya ekran görüntüsü gibi eklemeyi seçtiğin bilgileri işleriz. Yalnızca sorunu yanıtlamak veya bildirilen problemi araştırmak için gerekenleri kullanırız (GDPR Madde 6(1)(f)); yasal gizlilik taleplerinin hukuki dayanağı yukarıda açıklanmıştır. Parola veya kimlik doğrulama bağlantısı gönderme.'), p('{{supportRetention}}')] },
        { id: 'rights', heading: 'Hakların', blocks: [p('Geçerli yasal koşullar çerçevesinde kişisel verilerine erişim, düzeltme, silme veya işlemenin kısıtlanmasını isteyebilirsin. Veri taşınabilirliği, işlemenin otomatik olduğu ve rızaya ya da sözleşmeye dayandığı durumlarda geçerlidir. İşleme rızaya dayanıyorsa önceki işlemenin hukuka uygunluğunu etkilemeden rızanı ileriye dönük olarak geri çekebilirsin.'), p('{{publicEmail}} adresine yaz. Normalde gereksiz gecikme olmadan ve bir ay içinde yanıt veririz. Yasanın izin verdiği bir uzatma gerekiyorsa nedenini ilk ay içinde açıklarız. {{deletionVerification}}'), p('Yaşadığın, çalıştığın veya ihlal olduğunu düşündüğün yerdeki makam dahil bir veri koruma makamına şikâyet edebilirsin. Bu sağlayıcıdan sorumlu makam: {{authorityName}}, {{authorityStreet}}, {{authorityPostalCity}}, {{authorityCountry}}. Bilgi ve şikâyet iletişimi: https://www.lda.bayern.de/.')] },
        { id: 'objection', heading: 'İtiraz hakkın', blocks: [p('İşleme GDPR Madde 6(1)(f) hükmüne dayanıyorsa kendi özel durumunla ilgili nedenlerle istediğin zaman itiraz edebilirsin. {{publicEmail}} adresine yaz. Menfaatlerine, haklarına ve özgürlüklerine ağır basan zorlayıcı meşru gerekçeler gösteremezsek veya işleme hukuki taleplerin ileri sürülmesi, kullanılması ya da savunulması için gerekli değilse bu işlemeyi durdururuz.')] },
        { id: 'children', heading: 'Çocuklar ve ebeveynler', blocks: [p('Knucklebones Neon genel bir kitleye yönelik bir oyundur. Yaş sorusu içermez ve doğum tarihi istemez. Yerel oyun için dereceli hesap gerekmez. Çevrimiçi oyun, küçük yaştaki oyuncular için de burada açıklanan hesap ve oyun bilgilerini saklar.'), p('Küçük yaştaysan: uydurma bir takma ad kullan, parolanı gizli tut ve hesap veya gizlilik sorularında güvendiğin bir yetişkinden yardım iste. Takma adını ve oyun sonuçlarını başkaları görebilir. Bu oyunda oyuncu sohbeti, reklam veya ödeme yoktur.'), p('Ebeveynler ve vasiler bir çocuğun hesabı, verilere erişim veya silme hakkında {{publicEmail}} adresine yazabilir. Yalnızca hesabı belirlemek ve işlem yapma yetkisini doğrulamak için gerekli bilgileri isteriz. Geçerli hukuk ebeveyn izni gerektiriyorsa Apple hesabı kullanmak veya oynamaya devam etmek bu iznin yerine geçmez.')] },
        { id: 'automated-decisions', heading: 'Eşleştirme ve otomatik hesaplamalar', blocks: [p('Oyun, oyun verilerinden skorları, sıralamaları, açılan içerikleri ve uygun rakipleri otomatik olarak hesaplar; seni bilgisayar tarafından yönetilen bir rakiple de eşleştirebilir. Bu oyun işlevleri, GDPR Madde 22 anlamında senin hakkında hukuki veya benzer ölçüde önemli sonuçlar doğuran kararlar vermez.')] },
        { id: 'changes', heading: 'Tarih ve değişiklikler', blocks: [p('Son güncelleme: {{noticeDate}}. Oyun veya veri işleme biçimi değiştiğinde bu bildirimi güncelleriz. Güncel sürüm uygulamada ve herkese açık gizlilik sayfasında bulunur. Önemli değişiklikler, değişen işleme başlamadan önce açıklanır.')] },
      ],
    },
    support: {
      title: 'Destek ve iletişim',
      shortTitle: 'Destek',
      description: 'Knucklebones Neon, gizlilik ve hesaplar için yardım.',
      intro: 'Oyun sorunları, hesap yardımı veya gizlilik talepleri için bize ulaş.',
      sections: [
        { id: 'contact', heading: 'İletişim', blocks: [p('E-posta: {{publicEmail}}')] },
        { id: 'help', heading: 'Yardım edebileceğimiz konular', blocks: [list('Teknik sorunlar ve erişilebilirlik', 'Dereceli hesaplar ve takma adlar', 'Gizlilik hakları ve hesap silme', 'Güvenlik veya kötüye kullanım bildirimleri', 'Ebeveynlerin bir çocuğun hesabıyla ilgili soruları')] },
        { id: 'details', heading: 'Hangi bilgileri eklemelisin', blocks: [p('Ne olduğunu açıkla ve uygulama veya tarayıcı sürümünü belirt. Takma adını veya doğrulanmış hesap e-postanı yalnızca hesabı bulmak için gerekiyorsa ekle. Ekran görüntülerinden başkalarının özel bilgilerini kaldır.')] },
        { id: 'credentials', heading: 'Giriş bilgilerini gizli tut', blocks: [p('Parolanı, giriş veya kurtarma bağlantını, erişim belirtecini, Apple yetkilendirme kodunu ya da başka birinin özel verilerini asla gönderme. Bu bilgileri e-posta ile istemeyiz.')] },
        { id: 'handling', heading: 'Taleplerin işlenmesi', blocks: [p('{{deletionVerification}}'), p('{{supportProcessing}}'), p('{{supportRetention}}'), p('Yasal gizlilik talepleri normalde bir ay içinde yanıtlanır; izin verilen bir uzatma ve nedeni de bu süre içinde açıklanır.')] },
      ],
    },
    'delete-account': {
      title: 'Hesabını sil',
      shortTitle: 'Hesabı sil',
      description: 'Knucklebones Neon dereceli hesabını uygulama içinde veya dışında silme yolu.',
      intro: 'Dereceli hesabını silmek kalıcıdır. Hesap olmadan yerel oynamaya devam edebilirsin.',
      sections: [
        { id: 'in-app', heading: 'Uygulama içinde silme', blocks: [list('Ana sayfadan profilini aç.', 'Hesap kontrollerini aç.', 'Hesabı sil seçeneğini belirle ve açıklamayı oku.', 'Kalıcı silme işlemini onayla.')] },
        { id: 'server-data', heading: 'Neler silinir', blocks: [p('Oyun etkin bir maçı sonuçlandırır ve sunucudaki hesabını, profilini, ayarlarını, kuyruk ve sıralama kayıtlarını, maç ve hamle geçmişini, rünlerini ve ilerlemeni siler. Bu dereceli kimlik ve sonuçları uygulama üzerinden geri yüklenemez.')] },
        { id: 'local-data', heading: 'Cihazındaki çevrimdışı veriler', blocks: [p('Hesap silme oturumunu kapatır ve yerel hesap oturumunu ve önbelleğe alınmış profili temizler. Çevrimdışı ayarların, istatistiklerin ve önbellekteki oyun dosyaların kalır. Bunları da kaldırmak için tarayıcıdan bu sitenin verilerini temizle. Android’de cihaz ayarlarından uygulamanın depolama alanını veya verilerini temizle. iOS’ta Uygulamayı Sil seçeneğini kullan; Uygulamayı Kaldır seçeneği belgeleri ve verileri saklar. Yalnızca cihaz verilerini temizlemek sunucu hesabını silmez.')] },
        { id: 'external', heading: 'Uygulama olmadan silme talebi', blocks: [p('{{publicEmail}} adresine yazarak Knucklebones Neon dereceli hesabının silinmesini istediğini belirt. Hâlâ erişebiliyorsan doğrulanmış hesap e-postanı kullan. Takma adını yalnızca hesabı bulmak için gerekiyorsa ekle. Giriş bilgilerini gönderme. Bir ebeveyn veya vasi de çocuğun hesabıyla ilgili bize ulaşabilir.')] },
        { id: 'verification', heading: 'Sahiplik kontrolü ve kalan kopyalar', blocks: [p('{{deletionVerification}}'), p('{{securityLogRetention}}'), p('{{backupRetention}}'), p('{{supportRetention}}')] },
        { id: 'apple', heading: 'Apple’a bağlı bir hesap', blocks: [p('Silme işlemi Apple ile giriş bağlantısını iptal etmeyi de dener. Geçici hatalar en fazla {{appleRevocationRetryDays}} gün boyunca yeniden denenir. Otomatik iptal tamamlanamazsa uygulamadaki talimatları izle veya Apple hesap ayarlarından uygulamanın bağlantısını kaldır. Bu, Apple hesabını silmez. Ayrı Game Center hesabın da silinmez.')] },
      ],
    },
  },
};
